### PR TITLE
fix: Replace dark mode logo

### PR DESCRIPTION
**Pull request by AmanNegi**
- Replaced `flowy_logo_dark_mode.svg` because it does not work as expected.
- Fixed Issue #2259  

### Feature Preview

Now it works as expected, I will link a working example as well.

https://user-images.githubusercontent.com/37607224/232262631-32de1b2b-60f9-4e5c-8d2c-75d722547927.mp4

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by Xazin** [comment]
Can you elaborate why a bigger SVG changes anything here?

**Comment by AmanNegi** [comment]
It's not only about the big size, but the complete file has been replaced. You might want to check the old file it renders black text only, which seems like an error in SVG code to me.

**Comment by Xazin** [comment]
> It's not only about the big size, but the complete file has been replaced. You might want to check the old file it renders black text only, which seems like an error in SVG code to me.

Ah alright. Was just curious, seems the old svg wasn't compounded either. 👍

**Comment by LucasXu0** [comment]
Closes https://github.com/AppFlowy-IO/AppFlowy/issues/2259.

**Comment by LucasXu0** [comment]
LGTM.

**Pull request merged**
