### PR TITLE
Feat/inline search

### PR DESCRIPTION
**Pull request by Xazin**
Enables the find and replace feature, credit: @MayurSMahajan 

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by Xazin** [comment]
cc @LucasXu0 @MayurSMahajan

**Comment by MayurSMahajan** [comment]
@Xazin is the MacOS Enter key press bug resolved?

**Comment by Xazin** [comment]
> @Xazin is the MacOS Enter key press bug resolved?

I am no longer able to reproduce it at least.

**Comment by LucasXu0** [comment]
# issues

1. we should match the AppFlowy's design when integrating this feature in AppFlowy
 1.1 the icon button should replaced with the appflowy one.
Screenshot 2023-09-27 at 16 00 37
 1.2 the color of the placeholder text shouldn't be same as the color of the input text.
 1.3 the icons.

2. we should disable the search menu when opening another page.
Screenshot 2023-09-27 at 16 05 07

3. sometimes, the background color should be clear after closing the search menu
Screenshot 2023-09-27 at 16 06 12

4. support case-sensitive.
5. the toolbar should disable when opening search menu.

**Pull request closed without merging**
