### PR TITLE
feat: Support markdown to italicize text

### PR DESCRIPTION
**Pull request by ankur12-1610**
Fixes: #1059
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@LucasXu0 implemented it just for `_`
`*` is still remaining, just wanted to make sure if the progress made is right?

**Comment by ankur12-1610** [comment]
> > @LucasXu0 implemented it just for `_` `*` is still remaining, just wanted to make sure if the progress made is right?
> 
> Hi @ankur12-1610. The implementation is correct, but we already have the same implementation for converting `_` to italicized text. Would you mind also implementing converting `*` to italicized text?

Yeah, I'm actually working on it just wanted to make sure that the way in which the code is written correct or not:sweat_smile:

**Comment by ankur12-1610** [comment]
@LucasXu0 I've tried to combine two event handlers in one, although I'm not sure if it is done correctly, can you please review:sweat_smile:?

**Comment by ankur12-1610** [comment]
@LucasXu0 can you please review the latest changes?

**Comment by LucasXu0** [comment]
This feature has been merged from another commit. Close this duplicated PR.

**Pull request closed without merging**
