### PR TITLE
Fixed Icon Issue in Linux

### PR DESCRIPTION
**Pull request by notd5a-alt**

### CODE REVIEW

**Review by pdckxd — COMMENTED** [review]
Looks like changes in this PR restore some latest update in TOT code base. Maybe it need to be rebased at first.

**Comment by notd5a-alt** [comment]
I dont know how to rebase, if you could help me that would be great.

**Comment by notd5a-alt** [comment]
rebased the patch.

**Comment by pdckxd** [comment]
@notd5a-alt , kindly check this link
https://stackoverflow.com/a/24527934

**Comment by notd5a-alt** [comment]
Ok i'm going to save us all the trouble, close this PR and reapply the changes to the latest pull and then reopen a PR.

**Pull request closed without merging**
