### PR TITLE
fix: correcting mistmatched json_serializable version

### PR DESCRIPTION
**Pull request by donlaiq**
I saw a few warnings in the installation process, and with these changes I think I'm fixing two of them:

**[WARNING]** json_serializable on lib/env_serde.dart:
The version constraint "^4.7.0" on json_annotation allows versions before 4.8.1 which is not allowed.

**[WARNING]** json_serializable on lib/colorscheme/colorscheme.dart:
The version constraint "^4.7.0" on json_annotation allows versions before 4.8.1 which is not allowed.

Hopefully, if everything goes well, and it's accepted, I'll try to fix the other ones.

### CODE REVIEW

**Comment by donlaiq** [comment]
Is there a way to run those test locally before to make the pull request?
I've undone my changes and run the following command (the one failing in https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5471271334/jobs/9963233326?pr=2944) from the frontend/rust-lib folder:

`RUST_LOG=info RUST_BACKTRACE=1 cargo test --no-default-features --features="rev-sqlite"`

But anyway, some tests are not passing. Maybe, it's because I'm running it from Linux Debian?

**Comment by LucasXu0** [comment]
@donlaiq It's not related to your PR. I'm fixing the CI issues now.

**Comment by Xazin** [comment]
Hey @donlaiq, the changes in this PR seem irrelevant to the title. Can we close this, or will you be working on it?

Feel free to jump into our discord if you have any questions.

**Comment by donlaiq** [comment]
Hello @Xazin, the PR removes 2 warnings in the installation process (attached images). So, actually it does what the title says, and I also explained it in my first comment.
After that, I did some changes to remove other warnings, but I didn't know that it will mix with this current PR, so I revert it.
Feel free to close it if you think it's irrelevant.

w1
w2

**Comment by Xazin** [comment]
> Hello @Xazin, the PR removes 2 warnings in the installation process (attached images). So, actually it does what the title says, and I also explained it in my first comment. After that, I did some changes to remove other warnings, but I didn't know that it will mix with this current PR, so I revert it. Feel free to close it if you think it's irrelevant.
> 
> w1 w2

There are no changes related to `pubspec.yaml` in the current diff. Seems you accidentally removed it, thus my previous comment.

**Comment by donlaiq** [comment]
Oh, I'm sorry about that @Xazin. It seems I messed it up with the revert.

**Comment by donlaiq** [comment]
By the way @Xazin, it seems this PR solve also the following kind of warnings during the installation process.
Hopefully, you can accept the changes, because I think I found the way of solving the next group of warnings, but I don't want to keep mixing the things up on this thread.
w3

**Comment by appflowy** [comment]
@donlaiq I close this PR. Please feel to reopen

**Pull request closed without merging**
