### PR TITLE
Added Greek language - Initial commit with some translations

### PR DESCRIPTION
**Pull request by antwnhsx**

### CODE REVIEW

**Comment by richardshiue** [comment]
Hi there @antwnhsx thanks for the contribution! Would you like to add Greek as an option to the settings page? You can follow the instructions at https://docs.appflowy.io/docs/documentation/appflowy/translation#add-an-unsupported-language . If not, I can do that for you.

**Comment by antwnhsx** [comment]
Hello Richard!

Yes! Excuse me, my bad, I am still new to pull requests and to
contributions. I will fix it as soon as I can.

Στις Τρί 12 Μαρ 2024 στις 4:09 π.μ., ο/η Richard Shiue <
***@***.***> έγραψε:

**Comment by antwnhsx** [comment]
I have trouble setting up the environment although everything builds, translation keeps 'disappearing'. Could you please add the language so I can continue pushing translations?

Sorry for the inconvenience.

**Comment by antwnhsx** [comment]
I have trouble setting up the environment although everything builds, translation keeps 'disapearing'. Could you please add the language so I can continue pushing translations?

Sorry for the inconvenience.

**Comment by LucasXu0** [comment]
@antwnhsx I added the Greek language in the settings page.

**Review by LucasXu0 — APPROVED** [review]

**Comment by richardshiue** [comment]
Hi @antwnhsx, we tried to add the settings commit into your branch but something went wrong along the way. Would you like to try again by opening a new PR?

**Pull request closed without merging**
