### PR TITLE
feat: trigger shortcut event by character

### PR DESCRIPTION
**Pull request by LucasXu0**
* Define a new parameter called `character` to `shortcut_event`.
* Trigger the shortcut by checking whether the character is the same as the character of the `RawKeyEvent` in `onKey` callback,

### CODE REVIEW

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/AppFlowy/issues/2080
https://github.com/AppFlowy-IO/AppFlowy/issues/2070
https://github.com/AppFlowy-IO/AppFlowy/issues/1876

**Comment by LucasXu0** [comment]
For example, we use `slash` as the command before, and we should use the character `/` trigger the shortcut now.

Screenshot 2023-03-24 at 10 47 45

FYI, @Xazin

**Comment by LucasXu0** [comment]
#2098

**Comment by a-wallen** [comment]
@LucasXu0 https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

fixes https://github.com/AppFlowy-IO/AppFlowy/issues/1876
fixes https://github.com/AppFlowy-IO/AppFlowy/issues/2080

**Comment by LucasXu0** [comment]
FYI, @Xazin, @MayurSMahajan.

**Review by Xazin — APPROVED** [review]
Looks good.

Very clean way to implement it.

**Pull request merged**
