### PR TITLE
chore: update Russian translations [2]

### PR DESCRIPTION
**Pull request by Emilkyo**
Added more empty lines :)

### CODE REVIEW

**Comment by richardshiue** [comment]
Hi @Emilkyo, there are some merge conflicts here, could you take a look?

**Comment by Emilkyo** [comment]
Okay, I see

**Comment by Emilkyo** [comment]
> Hi @Emilkyo, there are some merge conflicts here, could you take a look?

Okay, I see

**Comment by Emilkyo** [comment]
I translated and replaced some lines with more correct ones for the language. Also I think that different declensions and meanings of sentences will need to be checked later in app itself, during use

**Review by richardshiue — APPROVED** [review]
LGTM

**Pull request merged**
