### PR TITLE
Issue #4244 removed Duplicate button labels for done and cancel

### PR DESCRIPTION
**Pull request by Kargatharaakash**
#4244

### CODE REVIEW

**Comment by math-GH** [comment]
Please check the other languages too if there is this label used.

**Comment by Kargatharaakash** [comment]
#4244 removed Duplicate button labels for done and cancel kindly review

**Comment by richardshiue** [comment]
The deleted token is currently being used, hence the failed tests. You can replace such occurrences with the token without the uppercase

**Comment by Kargatharaakash** [comment]
#4244 removed Duplicate button labels for done and cancel and updated with lowercase kindly review

**Comment by richardshiue** [comment]
Hey there @Kargatharaakash. What I mean is that there are places in the code that actually use this token. You would need to replace them with the lowercase versions

image

**Pull request closed without merging**
