### PR TITLE
feat: support group by url in kanban board

### LINKED ISSUE #1175: [FR]: Support Group by the URL property in Kanban Board

### PR DESCRIPTION
**Pull request by zoli**
Closes #1175

### CODE REVIEW

**Comment by zoli** [comment]
@appflowy 

About the `get_cell_data_for_field` I looked at it but still couldn't figure out how to access `GridRevisionEditor`. It seems that I should access it through some grid manager but again I don't know how can I get the grid manager. I'm new to the codebase and rust so forgive me if I'm asking obvious things.

On first problem that I had which was deserliazing `URLTypeOptionPB` I looked into `CellDataDecoder` and that part seems fine, but `URLTypeOptionPB` is empty. I'm working on this feature with comparing the work done for group by checkbox and single/multi select there isn't much difference regarding the `CellDataDecoder` part.

**Comment by appflowy** [comment]
> `get_cell_data_for_field`

Got it. I think I know how to fix it. I am working on it and I will let you know after I push my local changes.

**Comment by appflowy** [comment]
I refactor the get_cell_data_for_field in this [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/1695/files#diff-804bcc48ba26a5782c45e04babce4a420ec013c1f5d3a504026df3d667fbd82fR79). And push my changes to your repo. 

```rust
fn generate_groups(
        field_rev: &FieldRevision,
        group_ctx: &Self::Context,
        _type_option: &Option<Self::TypeOptionType>,
    ) -> GeneratedGroupContext {
        // Read all the cells for the grouping field
        let cells = futures::executor::block_on(group_ctx.get_all_cells());

        // Generate the groups
        let group_configs = cells
            .into_iter()
            .flat_map(|value| value.into_url_field_cell_data())
            .map(|cell| {
                let group_id = cell.content.clone();
                let group_name = cell.content.clone();
                GeneratedGroupConfig {
                    group_rev: GroupRevision::new(group_id, group_name),
                    filter_content: cell.content.clone(),
                }
            })
            .collect();

        let no_status_group = Some(make_no_status_group(field_rev));
        GeneratedGroupContext {
            no_status_group,
            group_configs,
        }
    }
```

> On first problem that I had which was deserliazing URLTypeOptionPB I looked into CellDataDecoder and that part seems fine, but URLTypeOptionPB is empty. I'm working on this feature with comparing the work done for group by checkbox and single/multi select there isn't much difference regarding the CellDataDecoder part.

Would you mind helping me to locate these relative codes?

**Comment by zoli** [comment]
> I refactor the get_cell_data_for_field in this [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/1695/files#diff-804bcc48ba26a5782c45e04babce4a420ec013c1f5d3a504026df3d667fbd82fR79). And push my changes to your repo

Thanks, Now the group by url is working.

> Would you mind helping me to locate these relative codes?

The type option in url controller [here](https://github.com/zoli/AppFlowy/blob/e20c429f62d2b1498f1e990346f8dbfeddaed66f/frontend/rust-lib/flowy-grid/src/services/group/controller_impls/url_controller.rs#L108) which is of `URLTypeOptionPB` type is empty, But this is not the case for single select controller [here](https://github.com/zoli/AppFlowy/blob/e20c429f62d2b1498f1e990346f8dbfeddaed66f/frontend/rust-lib/flowy-grid/src/services/group/controller_impls/select_option_controller/single_select_controller.rs#L93) which is of `SingleSelectTypeOptionPB` type.
It seems to me that the data isn't getting deserialized in the url case, but I don't see the difference between `URLTypeOptionPB` and `SingleSelectTypeOptionPB`.
BTW after your changes there is no need to the [type option](https://github.com/zoli/AppFlowy/blob/e20c429f62d2b1498f1e990346f8dbfeddaed66f/frontend/rust-lib/flowy-grid/src/services/group/controller_impls/url_controller.rs#L108) in url controller anymore, But still I don't get why its empty.

**Comment by appflowy** [comment]
> Also now this seems close to ready. There seem to be a general group by tests [here](https://github.com/zoli/AppFlowy/blob/e20c429f62d2b1498f1e990346f8dbfeddaed66f/frontend/rust-lib/flowy-grid/tests/grid/group_test/test.rs). Should I add specific group by url tests?

Yep, adding tests would be better.

**Comment by appflowy** [comment]
> It seems to me that the data isn't getting deserialized in the url case, but I don't see the difference between `URLTypeOptionPB` and `SingleSelectTypeOptionPB`.

> It seems to me that the data isn't getting deserialized in the url case, but I don't see the difference between URLTypeOptionPB and SingleSelectTypeOptionPB.

Currently, the URLTypeOptionPB is empty. 
image

**Comment by zoli** [comment]
I think this is ready. Thanks in advance for the help & review.
Just to note on following [submit your first pull request guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request#keep-your-local-repository-up-to-date), I think while rebasing I messed and made @appflowy commits my commit. Maybe it was better to keep my old `git merge` habit :).

**Comment by appflowy** [comment]
> I think this is ready. Thanks in advance for the help & review. Just to note on following [submit your first pull request guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request#keep-your-local-repository-up-to-date), I think while rebasing I messed and made @appflowy commits my own commit. Maybe it was better to keep my old `git merge` habit :).

No problem. Will merge after the CI.

**Pull request merged**
