### PR TITLE
[WIP] feat: document icon on sidebar

### LINKED ISSUE #2918: [Bug] Icon added on a page should show in menu
### Bug Description

Currently, when we add an icon to any page, the icons in the menu corresponding to this page stay the same.
This is not really a bug, but a suggestion for improving UX. 

### How to Reproduce

1. Open AppFlowy
2. Create a new document page.
3. Add an Icon to the page.

### Expected Behavior

The icon should also be visible in the menu.

### Operating System

Windows 11

### AppFlowy Version(s)

0.2.4

### Screenshots

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
Title says all

### Feature Preview

resolves #2918

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by richardshiue** [comment]
This is a quick and dirty solution. The alternative is of course to parse the document for the icon before sending over the `viewPB`

**Comment by MayurSMahajan** [comment]
Hey Richard! From what I can understand, I have a doubt, we are not saving the new icon anywhere, so it will not be persistent, is that correct?

**Comment by richardshiue** [comment]
> Hey @richardshiue! From what I can understand, I have a doubt, we are not saving the new icon anywhere, so it will not be persistent, is that correct?

Hi Mayur, is it not being saved when you are testing this PR? It works fine on my end.

**Comment by MayurSMahajan** [comment]
Apologies, it worked the second time.

**Pull request closed without merging**
