### PR TITLE
ci: add .exe installer support for Windows releases #1305

### LINKED ISSUE #1305: [FR] Support .exe setup for Windows
### Description

It's a normal installation way on Windows. Please integrate the `.exe` setup installation way on the release page.

### Impact

The Windows user will be easier to install AppFlowy

### Additional Context

https://retroportalstudio.medium.com/creating-exe-executable-file-for-flutter-desktop-apps-windows-ea7c338465e

### PR DESCRIPTION
**Pull request by ramanverma2k**
This PR adds the ability to build and release easy to use executable installers for Windows OSs. fixes #1305 .

### CODE REVIEW

**Comment by appflowy** [comment]
@ramanverma2k Thank you for contributing. I will check it ASAP.

**Comment by yodatak** [comment]
Hello is the installer is instable in non administrator system ( cooporate windows have no admin right and can only install in the local folder , i think to be use as a coorporate tool it must be instable on non administrator system

**Comment by ramanverma2k** [comment]
It should work on non-administrative accounts as well. I don't see any reason why it wouldn't. Currently I don't have access to my Windows machine, So I can't really test it. If anyone can, then please do so and give feedback whether it makes any difference or not.

**Comment by LucasXu0** [comment]
I will merge it and find a non-admin Windows machine to test it.

**Pull request merged**
