### PR TITLE
Readme.md | Replaced social media hyperlinked text with icons.

### PR DESCRIPTION
**Pull request by Abubakrce19**
0-I replaced the simple Hyperlinked Website, Discord, Twitter text with with their icons. 1-This makes our readme.md file more interactive.
2-Now the user can go to appflowy social media handles with a single click on the particular social media icon, where the user want go!!
4-Any kind of improvement idea is appreciated
Rich difference:
image

Thank you!!

### CODE REVIEW

**Comment by Abubakrce19** [comment]
@factotvm 
@PabloCastellano 
@huyz 
@tisohjung

**Comment by Abubakrce19** [comment]
@appflowy Please have a look.
Thank you

**Comment by Abubakrce19** [comment]
> This spam is ridiculous. Banning in order?
> 
> https://github.com/marketplace/actions/spamtoberfest-pull-request-spam-checker
Sorry i didnt understand

**Comment by Abubakrce19** [comment]
> This spam is ridiculous. Banning in order?
> 
> https://github.com/marketplace/actions/spamtoberfest-pull-request-spam-checker

?

**Comment by Abubakrce19** [comment]
@huyz 
@LucasXu0 
plz have a look

**Comment by huyz** [comment]
@Abubakrce19 why do you keep contacting me?

**Comment by PabloCastellano** [comment]
@Abubakrce19 WTF stop contacting people, you also contacted me and edited the message

**Comment by Abubakrce19** [comment]
> @Abubakrce19 WTF stop contacting people, you also mentioned me and removed the message.
> 
> Maintainers will review the PR when they have time. You don't need to be pushy. Stop wasting people's time.


oh i though u r the maintainer

**Comment by annieappflowy** [comment]
Hi @Abubakrce19 , can you please create a new PR for this and request me to review?
In general, it takes some time for maintainers to process PRs. When your PRs are waiting for review, please don't spam on the threads.

**Pull request closed without merging**
