### PR TITLE
Feat : Add Language Selector on Welcome Screen

### PR DESCRIPTION
**Pull request by Om-Gujarathi**
Added Language Selector on Welcome Screen as discussed in #2069 

QS

### CODE REVIEW

**Comment by a-wallen** [comment]
The integration tests failed on macOS since Flutter 3.7.5 dropped OpenGL support. This PR integration tests for that reason, probably unrelated to your change.
I also amended your commit to follow the acceptable format for this repo.
The PR also failed `Flutter-CI` due to reasons unrelated to this PR. We accidentally checked in code with analyzer errors. Hopefully, everything passes on this time around.

**Comment by a-wallen** [comment]
Even if all the CI Actions pass, this test needs widget tests. Please add them at your convenience.

**Comment by LucasXu0** [comment]
Hey, @Om-Gujarathi. I will mark it as Ready once you add the test code.

**Comment by annieappflowy** [comment]
Pending for 2 weeks
Can we merge it and add tests?

**Comment by a-wallen** [comment]
@annieappflowy the code is LGTM. I didn't merge because it didn't have tests. If we need this ASAP, then I am comfortable merging it and adding tests later.

**Review by a-wallen — APPROVED** [review]

**Comment by LucasXu0** [comment]
Screenshot 2023-05-03 at 15 49 25

The style of the language selector has been updated recently. I think we should adjust to the new style in this PR since the button currently looks non-operational.

cc @Om-Gujarathi @hyj1204

**Pull request closed without merging**
