### PR TITLE
fix: removed space under grid

### LINKED ISSUE #4314: [Bug] [FR] Unnecessary empty space of grids
### Bug Description

We are able to see empty space when scrolling instead of data
image
image

### How to Reproduce

populate enough data to get a scroll bar

### Expected Behavior

not having unnecessary empty space

### Operating System

windows amd64

### AppFlowy Version(s)

v0.4.1

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ilyes-ced**
### Feature Preview

resolves #4314

i am not sure if that space is intended or did someone forget to change from 200 bottom padding in `AppFlowy/frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/footer/grid_footer.dart`
#### old
```dart
class GridRowBottomBar extends StatelessWidget {
  const GridRowBottomBar({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: GridSize.footerContentInsets,
      height: GridSize.footerHeight,
      margin: const EdgeInsets.only(bottom: 200, top: 8),
      child: const GridAddRowButton(),
    );
  }
```
#### new
```dart
class GridRowBottomBar extends StatelessWidget {
  const GridRowBottomBar({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: GridSize.footerContentInsets,
      height: GridSize.footerHeight,
      margin: const EdgeInsets.only(bottom: 8, top: 8),
      child: const GridAddRowButton(),
    );
  }
```

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@lielfr Please sign the CLA.

**Review by richardshiue — APPROVED** [review]

**Comment by ilyes-ced** [comment]
i think i have signed the CLA

**Comment by Xazin** [comment]
Seems a lot of tests related to grid are failing after these changes. Can you take a look?

**Comment by ilyes-ced** [comment]
can you tell me how to run the test please, i am fairly new to flutter and to this project and i cant find the documentation for testing. thank you

**Comment by LucasXu0** [comment]
> can you tell me how to run the tests please, i am fairly new to flutter and to this project and i cant find the documentation for testing. thank you

It's a known issue. Merging the main branch will fix it.

**Comment by ilyes-ced** [comment]
i merged with main, i don't know if this enough 
and i still don't know how to run the tests

**Pull request merged**
