### PR TITLE
Small fixes for `docker-compose up` command's error and warning

### PR DESCRIPTION
**Pull request by texhno**
When I run `docker-compose up` command I'm getting the following error:
```
app_1  | (app_flowy:1): dbind-WARNING **: 20:06:32.776: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
app_1  | libGL error: MESA-LOADER: failed to retrieve device information
app_1  | [xcb] Unknown sequence number while processing queue
app_1  | [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
app_1  | [xcb] Aborting, sorry about that.
app_1  | app_flowy: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
appflowy_app_1 exited with code 139
```
I searched on the Internet and found some solutions, feel free to use them if you consider them useful.

Lines below are fixing the `libGL error: MESA-LOADER: failed to retrieve device information` and following `[xcb]` messages
```
devices:
      - "/dev/dri:/dev/dri"  # fixes MESA-LOADER error
```
Line `- NO_AT_BRIDGE=1`  is fixing the `(app_flowy:1): dbind-WARNING **: 20:06:32.776: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

### CODE REVIEW

**Comment by MikeWallaceDev** [comment]
I ran this on my Linux system, I didn't see anything bad, but I didn't see anything good either. As before, AppFlowy ran, but the screen did not render (it stays white)

**Comment by appflowy** [comment]
Hi @texhno, you could talk with @PabloCastellano, he made the docker file.

FYI:
https://github.com/AppFlowy-IO/AppFlowy/pull/348
https://github.com/AppFlowy-IO/AppFlowy/pull/373

**Comment by MikeWallaceDev** [comment]
Actually @appflowy , what I meant in our conversation is that since the dockerfile has advanced a lot since this PR @PabloCastellano should take a look at this PR, see if there is anything we can use to improve the current dockerfile and then close this PR.

Using this PR will involve rebasing, and conflicts...  Might as well just take any relevant code and create a new PR.

**Comment by PabloCastellano** [comment]
Hello. I can't try it now but I think the dbind warning was fixed by mounting the dbus unix socket inside the container.

as for `devices: "/dev/dri:/dev/dri"`, this device is also mounted now in the container, using `volumes` instead of `devices` though. Is there any major difference?

**Comment by micwoj92** [comment]
This branch has conflicts that must be resolved

**Comment by MikeWallaceDev** [comment]
I fixed the commit message so that the CI would pass.

**Pull request merged**
