### PR TITLE
Push docker image to Docker Hub

### LINKED ISSUE #344: [FR] Publish docker images to Docker Hub
**1~3 main use cases of the proposed feature**

As a Linux user, I want to try AppFlowy asap and avoid compiling anything. Since there is already support to create a docker image, the last missing part is publishing this image to docker hub, so that other can just download and execute it.

Though it would be more convenient to automatically upload it using CI, at the moment you can use [my image](https://hub.docker.com/repository/docker/pablocastellano/appflowy) as example.

```
docker run --rm \
  -v $HOME/.Xauthority:/root/.Xauthority:rw \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev/dri:/dev/dri \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  -v appflowy-data:/home/makepkg \
  -e DISPLAY=${DISPLAY} \
  pablocastellano/appflowy
```

**what types of users can benefit from using your proposed feature**

All users, including developers.

**Additional context**

image

### PR DESCRIPTION
**Pull request by PabloCastellano**
Fixes #344 

NOTE: For it to work, we need an admin to configure an account in Docker Hub and set the credentials in environment variables in GithUb as explained in https://docs.docker.com/ci-cd/github-actions/#set-up-a-docker-project

### CODE REVIEW

**Comment by abitrolly** [comment]
Would be nice to get some docs how to run this as well.

**Comment by PabloCastellano** [comment]
@abitrolly There are already instructions! Check out https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/installing-with-docker

Once https://github.com/AppFlowy-IO/AppFlowy/pull/345 is merged the user will be able to start AppFlowy with just `docker-compose up` without having to compile anything, just downloading the image.

**Comment by abitrolly** [comment]
There is only a single container, so I would prefer just a single command that could be run without repository checkout. It is also not clear where the user data is saved. In the proposed setup it looks like the data is lost when container is restarted.

**Comment by PabloCastellano** [comment]
@abitrolly Good point! Sure I can also improve that. Could you guide me and tell me what files should we persist? So far I see that the following files are created inside the container:

* flowy/
    * kv.db
    * flowy-client.log.2022-02-20
    * 257c5418-68be-469d-8d29-b9f1963c2dc1/flowy-database.db

Is that all?

**Comment by abitrolly** [comment]
Well, I've just discovered the app to see what can it do. :D

This is what is created by a standalone app on Linux.
```
/home/anatoli/Documents/flowy/flowy-client.log.2022-02-19
/home/anatoli/Documents/flowy/flowy-client.log.2022-02-20
/home/anatoli/Documents/flowy/kv.db
/home/anatoli/Documents/flowy/d4d2b51c-43a4-4b72-837d-559d907e6c6e
/home/anatoli/Documents/flowy/d4d2b51c-43a4-4b72-837d-559d907e6c6e/flowy-database.db
```

**Comment by appflowy** [comment]
@PabloCastellano Yep, the application data is saved in flowy/ folder.

**Comment by appflowy** [comment]
@PabloCastellano I have tested the CI. The image has been published in [here](https://hub.docker.com/repository/docker/appflowyio/appflowy_client).

**Comment by PabloCastellano** [comment]
@appflowy Great!! I've tested it and works fine. Good work.

**Comment by abitrolly** [comment]
Why is it called `applflowy_client` and not just `appflowy`?

**Comment by PabloCastellano** [comment]
@abitrolly Not sure why @appflowy changed it in the last minute

**Comment by tenneck** [comment]
This is great, thank you guys!
Do you also plan to release a linux/arm64 version on Docker Hub, which can be used on a Raspberry Pi for example?

**Pull request merged**
