### PR TITLE
fix: PR #2414

### PR DESCRIPTION
**Pull request by vuzzer**
### Feature Preview

---

#### PR Checklist

it follows the PR #2414
removed spaces to some dart file, fixed tests, and added spaces in other language files.

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by annieappflowy** [comment]
@vuzzer , did you commit in a different GitHub account than vuzzer?  CLA is blocking the progress because parfait kouassi has not signed according to the message above.

**Comment by vuzzer** [comment]
Hey @annieappflowy, Parfait Kouassi is not my github account name. My account name is **Vuzzer** (https://github.com/vuzzer). 
I don't understand why **CLA** recognizes **Parfait Kouassi** as being linked to a github account. The problem persists since the first PR. 
All my PR are done from my github **Vuzzer** account (https://github.com/vuzzer). Could you help me to solve this problem?

**Comment by richardshiue** [comment]
Hello @vuzzer, perhaps it is your local git commit author setup. You can try to follow the instructions in the following links to set your commit username and email

- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address
- https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by LucasXu0** [comment]
I will close it since there're no changes, and please create a new pull request when it's ready.

**Pull request closed without merging**
