### PR TITLE
fix: closing rename dialog on escape key press

### PR DESCRIPTION
**Pull request by ChiragKr04**
#809

### CODE REVIEW

**Comment by vincentdchan** [comment]
Wow, it's awesome. Could you squash your commits into one commit?

**Comment by ChiragKr04** [comment]
> Wow, it's awesome. Could you squash your commits into one commit?

Thanks!!. How do I do that!?

**Comment by vincentdchan** [comment]
https://www.git-tower.com/learn/git/faq/git-squash

**Comment by vincentdchan** [comment]
https://www.internalpointers.com/post/squash-commits-into-one-git

**Pull request closed without merging**
