### PR TITLE
chore: move russian translation file from CRLF to LF

### PR DESCRIPTION
**Pull request by richardshiue**

### CODE REVIEW

**Comment by appflowy** [comment]
Is there any issues if we don't translate to LF?

**Comment by richardshiue** [comment]
> Are there any issues if we don't translate to LF?

No it's just for consistency's sake.

**Comment by appflowy** [comment]
If someone uses Windows to modify the file, then it will convert to CRLF. I think It is hard to maintain consistency.

**Comment by richardshiue** [comment]
Ahh I see. I was thinking that that wouldn't happen. Closing as completed.

**Pull request closed without merging**
