### PR TITLE
Fix windows release build

### PR DESCRIPTION
**Pull request by a-wallen**
On Windows, the dart script can't invoke `cargo make` to build the release application because the dart script owns a file that `cargo build` needs. As a result, `cargo build` hangs, which caused the timeout seen here: https://github.com/AppFlowy-IO/AppFlowy/issues/3161

As a fix, allowed calling the two parts of the script that clean the pubspec.yaml to exclude/include test dependencies.

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by a-wallen** [comment]
@LucasXu0 I ran the following commands (relace ref version with 0.2.9), which work on my machine. The macos and linux commands do the exact same thing that they did before. 

Is there a way to test this on CI? I don't want this to cause a release to not go through again.

I apologize to everyone that was affected by this issue.

```
          flutter config --enable-windows-desktop
          dart ./scripts/flutter_release_build/build_flowy.dart exclude-directives . ${{ github.ref_name }}
          cargo make --env APP_VERSION=${{ github.ref_name }} --profile production-windows-x86 appflowy
          dart ./scripts/flutter_release_build/build_flowy.dart include-directives . ${{ github.ref_name }}
```

**Comment by LucasXu0** [comment]
> @LucasXu0 I ran the following commands (relace ref version with 0.2.9), which work on my machine. The macos and linux commands do the exact same thing that they did before.
> 
> Is there a way to test this on CI? I don't want this to cause a release to not go through again.
> 
> I apologize to everyone that was affected by this issue.
> 
> ```
>           flutter config --enable-windows-desktop
>           dart ./scripts/flutter_release_build/build_flowy.dart exclude-directives . ${{ github.ref_name }}
>           cargo make --env APP_VERSION=${{ github.ref_name }} --profile production-windows-x86 appflowy
>           dart ./scripts/flutter_release_build/build_flowy.dart include-directives . ${{ github.ref_name }}
> ```

A release job will be triggered after you tag the new version in your repo. This allows you to check the released packages. e.g. https://github.com/LucasXu0/AppFlowy/releases/tag/0.2.9

**Comment by a-wallen** [comment]
> > @LucasXu0 I ran the following commands (relace ref version with 0.2.9), which work on my machine. The macos and linux commands do the exact same thing that they did before.
> > Is there a way to test this on CI? I don't want this to cause a release to not go through again.
> > I apologize to everyone that was affected by this issue.
> > ```
> >           flutter config --enable-windows-desktop
> >           dart ./scripts/flutter_release_build/build_flowy.dart exclude-directives . ${{ github.ref_name }}
> >           cargo make --env APP_VERSION=${{ github.ref_name }} --profile production-windows-x86 appflowy
> >           dart ./scripts/flutter_release_build/build_flowy.dart include-directives . ${{ github.ref_name }}
> > ```
> 
> A release job will be triggered after you tag the new version in your repo. This allows you to check the released packages. e.g. https://github.com/LucasXu0/AppFlowy/releases/tag/0.2.9

Thanks @LucasXu0, I'm validating the fix: https://github.com/a-wallen/AppFlowy/actions/runs/5872711990/job/15924735316

**Comment by a-wallen** [comment]
This seems to be working fine now: https://github.com/a-wallen/AppFlowy/actions/runs/5873329946/job/15926434646#step:10:374

**Comment by a-wallen** [comment]
Just checked with @appflowy about how to verify that the test artifacts aren't in the build.

image

Looks like all of this works fine now. 😮‍💨

**Pull request merged**
