### PR TITLE
refactor: cover node widget code

### LINKED ISSUE #2849: [Bug] add icon hover effect
### Bug Description

image

### How to Reproduce

Add an icon to a page
Hover on it

### Expected Behavior

The hover background area seems too large

### Operating System

Windows 11

### AppFlowy Version(s)

v0.2.2

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by richardshiue**
- less ternary widgets in build methods
- less magic values, the height of the cover is now strictly at 250 px.
- fixes #2849
- addresses https://github.com/AppFlowy-IO/AppFlowy/issues/2850#issuecomment-1598355075
- fixes bug where the trash icon has a slighly more opaque background than the `change cover` button
- bump up height of `add/remove icon`, `add cover`, etc. to 28 to follow the `change cover` button
- clicking on change cover or add icon will show the popover but won't hide the button itself any more (better imo)
- improve the appearance of the selected solid color in the cover picker popup
- renamed `cover_node_widget` to `document_header_node_widget`. These changes are code-level and file-level.

### Feature Preview

https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/12483b18-eb25-4754-b586-47122172bd9f

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by richardshiue** [comment]
Hello @LucasXu0, I've done some renaming here, such as `selectionType` to `coverType`, please let me know if this is appropriate or it's better to leave it as it was. I'd like to, if possible, rename this entire node widget to maybe documentHeader, headerArea or banner, as it not only contains the cover-related stuff, but also the document icon which is pretty confusing imo. Document banner is also the thing that says this page is in the trash, though.

**Comment by LucasXu0** [comment]
@richardshiue Finally, someone refactored the code. 👍🏻

1. Yes, it's OK to rename selectionType, just don't modify the value.
2. Sure you can rename the node widget to document header or some names more suitable. btw, `DocumentHeader` looks good to me.

**Comment by LucasXu0** [comment]
Screenshot 2023-06-26 at 15 46 05

In my opinion, the height should be the same as the icon size with padding, perhaps 20. Currently, there is too much empty space above the document.

**Comment by LucasXu0** [comment]
Other parts look good to me.

**Comment by richardshiue** [comment]
> 1. Yes, it's OK to rename selectionType, just don't modify the value.
> 2.  Sure you can rename the node widget to document header or some names more suitable. btw, DocumentHeader looks good to me.

Got it, I'll update the PR with changes

> In my opinion, the height should be the same as the icon size with padding, perhaps 20. Currently, there is too much empty space above the document.

Sure thing

**Pull request merged**
