### PR TITLE
fix: flutter windows ci

### PR DESCRIPTION
**Pull request by richardshiue**
title says all, we want the green checkmark

### Feature Preview

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by a-wallen** [comment]
@richardshiue, thanks for this. Does this fix the `Flutter-CI` job?

**Comment by Xazin** [comment]
Wow, literally was wondering what could be the cause on my PR..

@a-wallen I can try this on my PR, it's failing due to long file names.

**Comment by LucasXu0** [comment]
LGTM. I suppose we should add this config setup to the documentation.

**Comment by richardshiue** [comment]
> @richardshiue, thanks for this. Does this fix the `Flutter-CI` job?

Yes, I believe so.

> I suppose we should add this config setup to the documentation.

Right on

**Pull request merged**
