### PR TITLE
feat: backquote to code text

### LINKED ISSUE #1065: [FR] Support markdown to mark as code
To denote a word or phrase as code, enclose it in backticks (`).

eg `Hello World`

Reference: 
* https://github.com/AppFlowy-IO/AppFlowy/discussions/1100
* https://www.markdownguide.org/basic-syntax/

### PR DESCRIPTION
**Pull request by MrHeer**
Resolve #1065 

- [x] logic
- [x] test

### CODE REVIEW

**Comment by rileyhawk1417** [comment]
@MrHeer Looks good man, only the tests are left :)

**Comment by LucasXu0** [comment]
Hi, @MrHeer. Is this for the Hacktoberfest? I can merge on 10.1.

**Comment by MrHeer** [comment]
> Hi, @MrHeer. Is this for the Hacktoberfest? I can merge on Oct 1.

@LucasXu0 Thank you.

I am very interested in this project and would be very willing to contribute on an ongoing basis if there is a suitable issue.

**Comment by annieappflowy** [comment]
@MrHeer , thanks a lot for contributing to AppFlowy! You can track a list of contributor friendly issues [here](https://github.com/orgs/AppFlowy-IO/projects/5/views/4)
We hope to see you soon!

**Pull request merged**
