### PR TITLE
fix: on hover change_cover button correct mouse cursor

### PR DESCRIPTION
**Pull request by 1akhanBaheti**
### Feature Preview

https://github.com/AppFlowy-IO/AppFlowy/assets/94619783/c0fda096-aa81-4bba-979b-680df48dbab3

fixes https://github.com/AppFlowy-IO/AppFlowy/issues/3543

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by 1akhanBaheti** [comment]
when on_pressed was passed as null, hover effect & cursor was not changing.

**Review by richardshiue — CHANGES_REQUESTED** [review]
Hey there @1akhanBaheti, thanks for the contribution. This fixes the issue, but I think there is a better solution. The onPressed parameter to RawMaterialButton should be nullable. I think it's better to investigate why the argument passed into the changecover button is null. It opens a popup right after all.

**Comment by richardshiue** [comment]
Oh great. Yes exactly, you can change the popover trigger action to None and then trigger a PopoverController in the onPressed callback.

**Review by Xazin — APPROVED** [review]

**Review by richardshiue — APPROVED** [review]
LGTM

**Pull request merged**
