### PR TITLE
feat: wrote an installation script for Linux users to install AppFlowy (#2951)

### LINKED ISSUE #2951: [FR] Add support for installation via curl command
### Description

As a Linux user, I would like to be able to install the Appflowy application using the curl command. This would allow me to quickly download and install the application without downloading the binary file manually or through other installation methods (https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods/mac-windows-linux-packages/installing-on-linux).

### Impact

With this feature, users need not deal with the installation steps that require extracting, renaming, or copy-pasting.

### Additional Context

I want to contribute to this feature by creating the installation script.

### PR DESCRIPTION
**Pull request by roopeshsn**
### Feature Preview

With this installation script, AppFlowy can be installed using the curl command,

```
curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash
```

Here are the logs,

```
roopesh@roopesh-mi-notebook-14:~$ curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash
AppFlowy-IO/AppFlowy info checking GitHub for latest tag
AppFlowy-IO/AppFlowy info found version: 0.2.5 for 0.2.5/linux/amd64
._AppFlowy
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
AppFlowy/
AppFlowy/._appflowy.desktop.temp
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
AppFlowy/appflowy.desktop.temp
AppFlowy/._AppFlowy
.....
.....
.....
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
AppFlowy/lib/libflowy_infra_ui_plugin.so
AppFlowy/lib/._libflutter_linux_gtk.so
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
AppFlowy/lib/libflutter_linux_gtk.so
[sudo] password for roopesh: 
AppFlowy-IO/AppFlowy info installed /opt/AppFlowy
{"msg":"[🟢 INITIALIZE - Start]","line":117,"file":"flowy-folder2/src/manager.rs","workspace_id":"e3b239cb-c86c-406d-b3f2-1fff60ff885c","uid":214958025964785664}
{"msg":"[🔵 INITIALIZE - End]","line":117,"file":"flowy-folder2/src/manager.rs","workspace_id":"e3b239cb-c86c-406d-b3f2-1fff60ff885c","elapsed_milliseconds":46,"uid":214958025964785664}
Jul 11 13:06:32.741  INFO ThreadId(14) {"message":"Supabase config is empty, skip init supabase."}
{"msg":"Supabase config is empty, skip init supabase."}
Jul 11 13:06:32.866  INFO ThreadId(14) {"message":"Network type: Wifi"}
{"msg":"Network type: Wifi"}
Jul 11 13:06:32.871  INFO ThreadId(14) {"message":"Network type: Wifi"}
{"msg":"Network type: Wifi"}
```

fixes #2951 

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@roopeshsn Could you share the command line that specifies the version/tag?

**Comment by roopeshsn** [comment]
> @roopeshsn Could you share the command line that specifies the version/tag?

No that's not the version of the command line. That's the latest release of AppFlowy.

**Comment by LucasXu0** [comment]
So it only supports installing the latest version. Is it right?

**Comment by roopeshsn** [comment]
No, one can pass the previous version to install,

```
 curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash -s 0.2.5

```

**Comment by LucasXu0** [comment]
> No, one can pass the previous version to install,
> 
> ```
>  curl -sSL https://github.com/roopeshsn/AppFlowy/raw/installation-script/install.sh | bash -s 0.2.5
> ```

Nice. That's what I meant.

**Pull request merged**
