### PR TITLE
chore: update translations for id-ID

### PR DESCRIPTION
**Pull request by linkb15**
Describe the changes you have conducted here.

I have edited id-ID part only in the inlang.com 

Preview the messages on https://inlang.com/github.com/linkb15/AppFlowy .

### CODE REVIEW

**Comment by LucasXu0** [comment]
Hi, @linkb15. Did you generate all these translations using machine translation?

**Comment by Xazin** [comment]
> Hi, @linkb15. Did you generate all these translations using machine translation?

Looks like most of the changes are just formatting/re-ordering of the key value pairs.

**Comment by linkb15** [comment]
Hi @LucasXu0, it seems the PR includes some of the languages that I did not edit myself - My part is only for id-ID.

**Comment by LucasXu0** [comment]
@linkb15 yes. it looks like the inlang editor formats the json files.

**Pull request merged**
