### PR TITLE
feat(shortcuts): Add Shortcuts to Help Menu

### PR DESCRIPTION
**Pull request by AmanNegi**
- Added option of shortcuts in help menu
- Clicking on the shortcut leads to the `Shortcuts.md` file

Fix for Issue: #1761

### CODE REVIEW

**Review by MayurSMahajan — COMMENTED** [review]
Hey Aman! Thanks for contributing to AppFlowy. Make sure you follow the steps in this doc https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation#steps-to-modify-an-existing-translation to generate the LocaleKeys class, only then you will be able to access LocalKeys.questionBubble_shortcuts.tr().

After the build command you may want to restart the app.

**Comment by AmanNegi** [comment]
Hey there sorry I tried running those commands but unfortunately they result in more errors. After running those two commands I have several errors like the generated file is missing the fields.

As you can see here the generated file is missing these fields, even though no changes were made to them.
Screenshot from 2023-02-21 06-35-34

**Comment by MayurSMahajan** [comment]
I think after you do the `flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations`.
You should Clean+Rebuild All.

**Comment by AmanNegi** [comment]
Hey there, I tried that but I am still facing the same issue. Any idea regarding what I could be doing wrong? If possible could you please check it by running at your end?

**Comment by LucasXu0** [comment]
> Hey there, I tried that but I am still facing the same issue. Any idea regarding what I could be doing wrong? If possible could you please check it by running at your end?

Hey, @AmanNegi. You can just run `sh ./scripts/generate_language_files.sh` in the `frontend` directory to generate the language files.

```sh
# lucas.xu @ MacBook-Pro-6 in ~/Desktop/AppFlowy/frontend on git:main o [9:42:39]
$ sh ./scripts/generate_language_files.sh
```

**Comment by AmanNegi** [comment]
Hey there, it also results in the same error.

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. Just let me help to fix it.

**Comment by AmanNegi** [comment]
Hey there, thanks a lot! Is there something I need to do from my end as of now?

**Comment by annieappflowy** [comment]
@AmanNegi , he's traveling. He should be able to get back to you by this week. Thanks for contributing! Hope your PR can get merged soon :D

**Comment by AmanNegi** [comment]
Oh Great! I also hope it gets merged ;) 

Thanks a lot

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. I solved the conflicts and will merge this PR after the CI pass.

**Comment by AmanNegi** [comment]
@LucasXu0 Thanks a lot for helping me out 🙌

I want to contribute to this project further as well, could you tell me what I was doing wrong which was causing those errors in my local system?

Thanks a lot again 🙂🤗

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. I executed the below commands in the `frontend` directory to generate the language files.

```
# lucas.xu @ MacBook-Pro-6 in ~/Desktop/AppFlowy/frontend on git:main o [9:42:39]
$ sh ./scripts/generate_language_files.sh
```

Screenshot 2023-03-02 at 15 53 28

If you still run into this problem, just DM me on Discord.

**Comment by AmanNegi** [comment]
Oh yeah Thanks, Running the script resolves the issues 🎉

Also, your theme looks cool😎

**Comment by LucasXu0** [comment]
> Also, your theme looks cool😎

😁 Here's the theme link. https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode

**Pull request merged**
