### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by fabiograz**

### CODE REVIEW

**Comment by MikeWallaceDev** [comment]
Wow, thank you so much @fabiograz !  You just opened up AppFlowy to a whole new country! :)

**Comment by MikeWallaceDev** [comment]
@fabiograz I believe that the filename is in an incorrect format. file is named it_it.json but it should be named it-IT.json, or just it.json
The text will not currently be detected by the system as you have not added it to the application. There is a [wiki page](https://github.com/AppFlowy-IO/appflowy/wiki/Translation) with the required steps to do so. I can help you out if you need :) (Honestly, it's much faster if I just do it myself, but it's much more fun for you to be able to do it :) )

**Comment by annieappflowy** [comment]
bravissimo!

**Comment by fabiograz** [comment]
> 
HI @MikeWallaceDev, thanks for your advices.
I've:

- renamed it_it.json to it_IT.json
- added Locale('it_IT') in supportedLocales

I hope is correct now.


> @fabiograz I believe that the filename is in an incorrect format. file is named it_it.json but it should be named it-IT.json, or just it.json The text will not currently be detected by the system as you have not added it to the application. There is a [wiki page](https://github.com/AppFlowy-IO/appflowy/wiki/Translation) with the required steps to do so. I can help you out if you need :) (Honestly, it's much faster if I just do it myself, but it's much more fun for you to be able to do it :) )

**Review by MikeWallaceDev — APPROVED** [review]
Thank you Fabio.  All of Italy thanks you :)

LGTM!!

**Pull request merged**
