### PR TITLE
feat: photo gallery block + image improvements

### PR DESCRIPTION
**Pull request by Xazin**
This PR adds:
- Drop image(s) on Image Placeholder to mass insert
- Pick multiple images from local to mass insert image blocks
- New Photo Gallery block with a simple image browser mode
  - Can drop images both on the placeholder block but also the image browser to quickly insert an image. 
- Interactive Image Viewer with zoom, delete, and download _(for internal images hosted in cloud)_/open image _(for files and external images)_.

Relates: #5557 #2947 #5407 #5486 #4346

Closes: #5165 

### Feature Preview

**Windows**

https://github.com/user-attachments/assets/3bd1f3df-5858-443e-890f-34a9b3856560

**iOS**
TBD

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by Xazin** [comment]
Tests to be added before merging:
- [ ] Interactive Viewer from Gallery can go to next/previous
- [ ] Can delete an image from Interactive Viewer in a Gallery
- [ ] Can delete an image from a Gallery through hovering on it's thumbnail
- [ ] Can insert an image to a Gallery with existing images
- [ ] Image block can insert multiple image nodes at the same time

**Comment by emmggi** [comment]
At last. Thank you.

**Comment by Xazin** [comment]
> At last. I love this. Thank you.
> 
> 
> 
> @Xazin One question however: I see there's a separate block. If I create a regular image block will it convert it to an album block if I drag more on it?

No it won't, but we can definitely add this behavior quite easily.

**Comment by emmggi** [comment]
Yeah we should. Converting them manually would be a bother and if we were to pick album blocks always from the start to future-proof, we wouldn't need an image block anymore then.

**Pull request merged**
