### PR TITLE
fix: fix integration tests

### PR DESCRIPTION
**Pull request by richardshiue**
### Feature Preview

---

#### PR Checklist

- [ ] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by Xazin** [comment]
The tests are failing because we don't add the event to check the initial screen size and thus had it collapsed by default.

This just has it expanded by default no?

**Comment by Xazin** [comment]
We can consider mocking the `window_manager` channel in `initializeAppFlowy` (tests). And have the creation of the HomeSettingBloc be something like:
```
return HomeSettingBloc(
  ...
)..add(
    HomeSettingEvent.checkScreenSize(
      (await windowManager.getSize()).width,
    ),
  );
```

**Comment by Xazin** [comment]
I believe tests will still fail unless we mock the window_manager.

**Comment by richardshiue** [comment]
> This just has it expanded by default no?

Yes. This was a bad fix

**Comment by richardshiue** [comment]
> This just has it expanded by default no?

Yes this was a bad fix.

**Review by Xazin — APPROVED** [review]

**Pull request merged**
