### PR TITLE
fix(appflowy_flutter): Flutter Version Reset Error

### PR DESCRIPTION
**Pull request by AmanNegi**
- `flutter channel stable` was causing the FlutterSDK to upgrade to its latest version.
- Added code to fix this behavior.
- Tested on Windows and Linux.

Issue: #1912

### CODE REVIEW

**Comment by LucasXu0** [comment]
Hi, @AmanNegi.

The option `-P` is invalid on macOS.

```bash
AppFlowy : Setting up Flutter
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Unhandled exception:
```

**Comment by AmanNegi** [comment]
Hey @LucasXu0, I have fixed the issue. Could you please test it now, I don't have any `MacOS` device so I can't test sorry :cry:.

**Comment by LucasXu0** [comment]
Okay. Let me try it.

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. The script will complain as the below pic shows if the developer uses the other version of Flutter. Because the script switches to the Flutter path but doesn't switch back.

Screenshot 2023-03-08 at 14 08 38

**Comment by AmanNegi** [comment]
Yep, thanks for pointing that out! I will fix that behavior.

**Comment by AmanNegi** [comment]
@LucasXu0 Could you please check if the changes I made, fix the issue that we were facing?

**Comment by LucasXu0** [comment]
Hi, @AmanNegi. LGTM. And I change the text format from CTLF to LF.

**Pull request merged**
