### PR TITLE
feat: context menu on right-click

### PR DESCRIPTION
**Pull request by aryanA101a**
### Feature Preview

---
#3135 

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by aryanA101a** [comment]
@Xazin I have implemented the feature except for the "relative to mouse" part.
Please check and tell me If I am heading in the right direction.

**Comment by aryanA101a** [comment]
@Xazin Please provide feedback

**Comment by aryanA101a** [comment]
Hi, @LucasXu0. I have made some modifications to remove the redundancy, and the functionality is as we want it to be.
But I am running into an issue with an integration test. Specifically this one: `'context menu opens up for favorites'`
I would appreciate some guidance to continue.

**Comment by LucasXu0** [comment]
It's not a suitable solution for this issue because the position of the popover action list will not track the touch point; it only appears in the middle of the view item wherever you click.

the better way in my mind is to 

1. Modify `AppFlowyPopover` to allow it to appear via a `SecondaryTap`. Currently, the `triggerActions` in `AppFlowyPopover` support the following three ways.
```dart
class PopoverTriggerFlags {
  static const int none = 0x00;
  static const int click = 0x01;
  static const int hover = 0x02;
}
```

2. Wrap the view item with a new popover that supports SecondaryTap and use secondaryTap as the flag.
3. Wrap the "View More" action button with the new popover and use the click as the flag.

**Comment by aryanA101a** [comment]
@LucasXu0 thats a nice approach.
When I modified the AppFlowyPopover wrapped over viewmore button, to include the click flag at the same time I commented the onPressed of the viewmore button, I found that on tapping the viewmore button: popup opens up and closes at the same time.
Then to investigate I added a break point to popover widget's deactivate method. That was the case, deactivate was being called as soon as the popup opened. I think hover is causing this issue because when I removed the FlowyHover from the viewitem, it worked.

**Comment by Xazin** [comment]
Hey @aryanA101a, are you still working on this? Do you need assistance?

Feel free to hit me up in our Discord channel, prefer the `#flutter-101` channel :+1:

**Comment by Xazin** [comment]
I'm going to close this due to inactivity, feel free to open a PR again with the final work.

**Pull request closed without merging**
