### PR TITLE
feat: Underline node parser implementation

### PR DESCRIPTION
**Pull request by glunkad**
# Description
Underline parser implementation to support markdown code format

### Feature Preview
 #1834 
---

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@glunkad. I think you may have misunderstood the issue. The underline style is a part of Delta, not a Node, and there is not a node called 'underline', but rather a text style referred to as 'underline'.

**Comment by glunkad** [comment]
@LucasXu0 , 
Sorry my bad will make the changes asap.

**Comment by glunkad** [comment]
Hey @LucasXu0 , 
can you please let me know in which file we are supposed to add it or create a new file.

**Comment by Xazin** [comment]
Closed for now as the related issue has been marked as completed, please reach out on Discord if we can provide further assistance.

**Pull request closed without merging**
