### PR TITLE
chore: improve number format display strings

### PR DESCRIPTION
**Pull request by richardshiue**

### CODE REVIEW

**Comment by richardshiue** [comment]
Or should we localize them?

**Comment by appflowy** [comment]
Wow, that's awesome!

**Comment by appflowy** [comment]
> Or should we localize them?

I check out how notion handles this. It seems the same as AppFlowy.

**Comment by richardshiue** [comment]
> > Or should we localize them?
> 
> I check out how notion handles this. It seems the same as AppFlowy.

Awesome, then I think this is good to go.

**Pull request merged**
