### PR TITLE
Add hotkey to reset app scale

### PR DESCRIPTION
**Pull request by Trapiz**
Use the Ctrl+0 or Meta+0 shortcut to reset the app scale to 1

[Scale demo.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/50213029/8aa3e18a-eefc-43a5-ba6c-f8a8cdc01ecb)

### Feature Preview

[implements](https://github.com/Appflowy-IO/AppFlowy/issues/5340)

---

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by Trapiz** [comment]
A question I do have is whether I should be writing tests for this. I couldn't find any tests that were checking the scaling up or down, so I didn't add a test for resetting the scale. I'm willing to write some tests for scaling and resetting said scale if you feel it's needed to write tests for this

**Comment by LucasXu0** [comment]
> A question I do have is whether I should be writing tests for this. I couldn't find any tests that were checking the scaling up or down, so I didn't add a test for resetting the scale. I'm willing to write some tests for scaling and resetting said scale if you feel it's needed to write tests for this

It would be great if you could add both tests.

**Comment by Trapiz** [comment]
> > A question I do have is whether I should be writing tests for this. I couldn't find any tests that were checking the scaling up or down, so I didn't add a test for resetting the scale. I'm willing to write some tests for scaling and resetting said scale if you feel it's needed to write tests for this
> 
> It would be great if you could add both tests.

Alright! I'll start looking into writing some tests. I converted the PR to draft for now.

**Comment by LucasXu0** [comment]
Hi, @Trapiz. Do you need any help? I can add a sample for your reference.

**Comment by Trapiz** [comment]
> Hi, @Trapiz. Do you need any help? I can add a sample for your reference.

I have looked into writing integration tests for this, but ran into the issue that the `IntegrationTestWidgetsFlutterBinding` binding is registered, and we also need the `ScaledWidgetsFlutterBinding` binding to be registered to allow scaling. But this is currently not possible to have two bindings registered at the same time. Me and @Xazin already talked about this and he also couldn't find a solution to this problem. I am going to see if I can pull this off with unit tests but I don't think they are going to turn out to be good test cases.

**Comment by Trapiz** [comment]
Hi @LucasXu0, a quick follow-up to the comment above, I have looked into writing some unit tests but quickly realized that this would not really be possible. There are really no standalone components to test, and as far as I know, no possibility to trigger key presses either. I feel like with the way that integration tests are currently set up, it's not possible to test this with our current implementation. Do you have any ideas on how to proceed?

**Comment by LucasXu0** [comment]
@Trapiz Let me see if I can do that.

**Comment by Xazin** [comment]
It's the same with unit test, except it's one of two bindings `AutomatedTestWidgetsFlutterBinding` or `LiveTestWidgetsFlutterBinding`.

**Pull request merged**
