### PR TITLE
fix: Filter UI popover pixels overflow with dynamic width and height

### PR DESCRIPTION
**Pull request by gitstart**
fixes [#2476](https://github.com/AppFlowy-IO/AppFlowy/issues/2476)
### PR Description
This PR fixes pixels overflow issue using by `Expandable` and text overflow rule `overflow: TextOverflow.ellipsis`.

### Issue Recording
https://www.loom.com/share/007bae93eabb4d819fc169d0239a15ff

###  Fix Recording
https://www.loom.com/share/0246a6cdc88f42558716c7364279b4aa

---
### PR Checklist
 - [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
 - [x] I've listed at least one issue that this PR fixes in the description above.
- [x]  I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
 - [x] All existing tests are passing.
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by a-wallen** [comment]
This PR needs a test in order to land.

Regardless, I'm not sure about this solution. `IntrinsicHeight` squares the complexity of the layout pass for it's subtree and `TextFilterEditor` already has an `IntrinsicHeight` widget. IIUC, the subtree would have a O((N²)²) layout pass. 
> This class is relatively expensive, because it adds a speculative layout pass before the final layout phase. Avoid using it where possible. In the worst case, this widget can result in a layout that is O(N²) in the depth of the tree.

I wonder if defining overflow behavior here (in `text.dart`) would solve this problem without squaring the layout pass for layer subtree.
https://github.com/AppFlowy-IO/AppFlowy/blob/f8f0599462ff0cca8b08dabd47f450147f3beecd/frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/widgets/filter/choicechip/text.dart#L120

**Comment by Xazin** [comment]
Couldn't we just eg. layout the title of the property different, eg. flexible in a row with some overflow behavior (ellipsis or clip).

That will probably more or less resolve the overflow, I'm not saying it will look the best though. But dynamically sized popovers could be a bit of a challenge.

**Comment by a-wallen** [comment]
> Couldn't we just eg. layout the title of the property different, eg. flexible in a row with some overflow behavior (ellipsis or clip).
> 
> That will probably more or less resolve the overflow, I'm not saying it will look the best though. But dynamically sized popovers could be a bit of a challenge.

Agreed. @gitstart, thanks for the contribution, could we try with a different approach? This is a solution to the problem, but a different approach might be more appropriate. I apologize for any confusion. Please message me on discord a-wallen#0603 if you need any help!

**Comment by gitstart** [comment]
> > Couldn't we just eg. layout the title of the property different, eg. flexible in a row with some overflow behavior (ellipsis or clip).
> > That will probably more or less resolve the overflow, I'm not saying it will look the best though. But dynamically sized popovers could be a bit of a challenge.
> 
> Agreed. @gitstart, thanks for the contribution, could we try with a different approach? This is a solution to the problem, but a different approach might be more appropriate. I apologize for any confusion. Please message me on discord a-wallen#0603 if you need any help!

Hello @a-wallen,
Requested changes are pushed using different approach. 
Thank you!.

**Review by a-wallen — APPROVED** [review]

**Review by Xazin — APPROVED** [review]

**Pull request merged**
