### PR TITLE
Table Plugin

### PR DESCRIPTION
**Pull request by zoli**
- New `Node` types 'table' and 'table/cell'. The 'table/cell' node for now contains single `TextNode`. All the data is kept in node attributes. Data related to 'table' like number of rows and columns are in 'table' node attributes and data related to each table cell is in 'table/cell' node attribute (cell height, position of cell its row and column).  The `TextNode` in table cell supports selection menu and toolbar but not all of them work inside the table cell (some of them are not applicable in table cell).
- Added `isApplicable` to `ContextMenuItem` so we can have context-base context menu
- Modified `backspaceEventHandler` so it won't move from one table cell to another cell and also handling backspace when the selection includes part of table cells and none table related nodes.
- Modified `_getNodeInOffset` so selection also works when we have multiple nodes in a single line (same y position). I will add more info on this in another comment.

### CODE REVIEW

**Comment by zoli** [comment]
Update: after [this](https://github.com/AppFlowy-IO/AppFlowy/pull/2120/commits/246ea1b74ff58ccdd70cf7df1604c722cb05097d), Now table cell can contain both text node and other node types. So image, math equation, table, etc are available in a table cell.

**Comment by zoli** [comment]
@LucasXu0 I should create a separate PR for appflowy editor changes in its separate repo?

**Comment by LucasXu0** [comment]
Hey, @zoli. No. You can just submit it in AppFlowy repo.

**Comment by zoli** [comment]
> Hey, @zoli. No. You can just submit it in AppFlowy repo.

I meant that I should create a separate PR for it in [Appflowy editor](https://github.com/AppFlowy-IO/appflowy-editor) repo. Because you removed the whole `appflowy_editor` here.

**Comment by zoli** [comment]
Nothing much here anymore, Table plugin code moved to appflowy-editor.

https://github.com/AppFlowy-IO/appflowy-editor/pull/62

**Comment by zoli** [comment]
Closing this, All the changes moved to appflowy-editor.

**Pull request closed without merging**
