### PR TITLE
feat: speeding up ci by disabling rust incremental build

### LINKED ISSUE #359: [CI] Speed up CI using GitHub build matrix
Speed up CI using GitHub [build matrix](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#using-a-build-matrix)

### PR DESCRIPTION
**Pull request by rubiagatra**
Fixes #359 

I am trying to speed up the CI process by disabling Rust Incremental build. https://matklad.github.io/2021/09/04/fast-rust-builds.html

### CODE REVIEW

**Comment by rubiagatra** [comment]
Please check this one out @LucasXu0 @annieappflowy

**Comment by rubiagatra** [comment]
I'll take a look, before PR ready

**Comment by appflowy** [comment]
> I'll take a look, before PR ready

Alright! Thank you

**Comment by rubiagatra** [comment]
I think there is not much improvement for build time when disabling incremental build.

I think I need more time to look at the project build configuration. What do you think @appflowy @LucasXu0?

references:
https://jondot.medium.com/8-steps-for-troubleshooting-your-rust-build-times-2ffc965fd13e 
https://nnethercote.github.io/perf-book/compile-times.html

**Comment by LucasXu0** [comment]
The same idea. The compiled products of Rust and Flutter are already cached. And each compilation may be running on a different machine, so the incremental build may not work whether enable or not.

**Comment by appflowy** [comment]
Hi @rubiagatra, this PR will be closed. Feel free to reopen it if you have any updates.

**Pull request closed without merging**
