### PR TITLE
fix: Missing the hand gesture icon in the text alignment options

### LINKED ISSUE #3475: [Bug] Missing the hand gesture icon in the text alignment options
### Bug Description

image

Hovering on left, center, or right shows a pointer rather than a hand

### How to Reproduce

Selecting a piece of text to trigger the format menu
Click on the text alignment
Hover on any alignment options

### Expected Behavior

Making it Consistent with other options by showing a hand gesture icon when hovering on any alignment options (left, center, and right)

### Operating System

macOS

### AppFlowy Version(s)

v0.3.2

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by narayann7**
### Feature Preview

https://github.com/AppFlowy-IO/AppFlowy/assets/64174995/37ff9b43-fe8f-4aa3-b368-8d334c1a2799

---
fixes #3475 

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Review by LucasXu0 — APPROVED** [review]

**Comment by LucasXu0** [comment]
> @LucasXu0 can you tell why some tests are failing?

I have restarted the test. let's wait for the result.

**Comment by narayann7** [comment]
@LucasXu0 what can be the possible reason of failing the tests previously

**Comment by LucasXu0** [comment]
> @LucasXu0 what can be the possible reason of failing the tests previously

it may be related to the test frame flush. the test condition failed because the next frame did not appear on time.

**Comment by narayann7** [comment]
changes are fine or any improvement required

**Comment by LucasXu0** [comment]
> changes are fine or any improvement required

LGTM.

**Pull request merged**
