### PR TITLE
refactor: updated at and created at

### LINKED ISSUE #2643: [Bug] auto-fill created time for existing rows
### Bug Description

After adding a "Created At" property, it only fills when a new row is added
image

### How to Reproduce

Add a Created At property to an existing database

### Expected Behavior

Pre-fill values for existing rows

### Operating System

Windows 11

### AppFlowy Version(s)

develop

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by appflowy**
refactor:
The updatedAt and createdAt  are reading the timestamp from the row instead of inserting a cell data. 

fix #2643 

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by appflowy** [comment]
@zoli FYI, I've refactored the logic of updatedAt and createdAt

**Comment by appflowy** [comment]
fix #2643

**Comment by zoli** [comment]
@appflowy, About updated at and created at not being editable I thought we can enable freeze by default when the feature is completed but also let the user disable the freeze and edit them manually. Also, I wasn't sure prefilling the rows created before is a good idea. Maybe its better to use the collab row `created_at` field?

**Comment by appflowy** [comment]
> @appflowy, About updated at and created at not being editable I thought we can enable freeze by default when the feature is completed but also let the user disable the freeze and edit them manually. Also, I wasn't sure prefilling the rows created before is a good idea. Maybe its better to use the collab row `created_at` field.

These two fields are designed to prevent manual editing. Yep, I use the row's created_at and updated_at define in collab crate.

**Pull request merged**
