### PR TITLE
feat: support windows platform in ci.yaml

### LINKED ISSUE #1248: [FR] Support windows platform in ci.yaml
### Description

Currently `ci.yaml` is not supported for the Windows platform, while `release.yml` is supported for all desktop platforms.

### Impact

Avoid unintended errors on windows.

### Additional Context

 Theoretically, we only need to migrate the logic of `release.yaml`

### PR DESCRIPTION
**Pull request by Ishanned**
fixes #1248

### CODE REVIEW

**Comment by Ishanned** [comment]
@LucasXu0 the window ci/build fails. Can you please guide?

**Comment by LucasXu0** [comment]
@Ishanned The name of the task that compiled Windows before was missing `_64`. Now it is `development(production)-windows-x86`. Would you mind helping to fix it together?

**Comment by LucasXu0** [comment]
I think your PR should also include the change here.

**Comment by Ishanned** [comment]
Sure I'll make the changes you asked

**Comment by Ishanned** [comment]
@LucasXu0 `development(production)-windows-x86` does not pass the test. Can you have a look again?

**Comment by LucasXu0** [comment]
My fault. Actually, I mean the task name is `development-windows-x86` or `production-windows-x86`.

**Comment by Ishanned** [comment]
Thank you!

**Pull request merged**
