### PR TITLE
feature: Translate new words to French

### LINKED ISSUE #462: [Bug] New words need to be translated
**Describe the bug**
We have new words in the en.json file that need to be translated.

I can translate them to french.
Please assign me !

### PR DESCRIPTION
**Pull request by MidouWebDev**
I worked on translating the new words added recently to French !

This PR closes #462

### CODE REVIEW

**Comment by MikeWallaceDev** [comment]
Oops, I was trying to edit the commit message but edited the PR message :)

@MidouWebDev can you please edit your commits and preprend them with "feature" or "fix" so that the checks will all pass? I can then merge this. Thanks :)

**Comment by MidouWebDev** [comment]
@MikeWallaceDev Would you clarify that please ?

**Comment by MikeWallaceDev** [comment]
Hi,
Every commit that you make has to be prefixed with either "feat:" or "fix:" or others.
For example "fix : added French translations for grid".

**Comment by appflowy** [comment]
@MidouWebDev  Thank you for contributing.  Could you mind updating your commit message, because it's not the AppFlowy Style.

image

You could check out this [guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request#commit-message-guidelines) for more information.

**Comment by MidouWebDev** [comment]
@appflowy ok

**Pull request merged**
