### PR TITLE
feat: Translations - Add cs-CZ language mutation

### PR DESCRIPTION
**Pull request by stmr**
I have translated all the stings via Inlang interface to **cs-CZ**.

Might need further polishing once the translations are displayed in the app as I was missing the context for some of them.

### CODE REVIEW

**Comment by PeterHero** [comment]
There is a typo on line 413 'nýzvu' -> 'názvu'

**Comment by stmr** [comment]
@PeterHero thanks for the catch! There will definitely be more typos and wrong translations as there was bug in Inlang that caused saving translated phrases to database to sometimes cut the phrase or leave out a part of it but it would be less work to get it to main first so I can fix typos/missaved phrases and alter some phrases context-wise in next iteration.

**Comment by PeterHero** [comment]
I agree. As a native speaker I find the translations legit.

**Comment by richardshiue** [comment]
Hey there @stmr, this is huge! Thanks for contributing. Would you like to take a stab at adding Czech to the actual application? Though a bit outdated and some parts need modification, this doc explains how you can do it https://docs.appflowy.io/docs/documentation/appflowy/translation#steps-to-add-new-language (the main difference is that the path is at frontend/appflowy_flutter, not frontend/app_flowy. Feel free to ask me if you run into trouble, and if it's not your cup of tea, let me know as well!

**Comment by stmr** [comment]
@richardshiue sure, I'll have a look later :-) My ultimate goal is to actually start contributing code so I'm just trying to get my hands on the project first

**Comment by richardshiue** [comment]
Awesome, sounds good

**Comment by richardshiue** [comment]
update: the doc has been updated https://docs.appflowy.io/docs/documentation/appflowy/translation#add-an-unsupported-language

**Pull request merged**
