### PR TITLE
Added Language Support for Urdu. Issue#3372

### LINKED ISSUE #3372: [FR] Urdu Language
### Description

With Urdu Language support people From Pakistan can use it easily.

### Impact

All Persons from Pakistan easily use this app. And by adding more language support app look more professional

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by duckcommit**
### Feature Preview

<!---

--!>
I had taken up an issue to add extra language support for the app. fixes #3372 https://github.com/AppFlowy-IO/AppFlowy/issues/3372

I have added support for Urdu as per the issue and tested it by running the app. Everything looks fine and has been translated properly.

Attatching Image below for reference.
image

Thank you. Hope this solves the issue.

### CODE REVIEW

**Comment by MayurSMahajan** [comment]
Great! Next time read these guidelines: https://docs.appflowy.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/code-submission-guidelines#commit-message-guidelines

**Review by MayurSMahajan — CHANGES_REQUESTED** [review]
Please exclude this launch.json file from your commit. cc: @richardshiue

**Comment by duckcommit** [comment]
> Great! Next time read these guidelines: https://docs.appflowy.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/code-submission-guidelines#commit-message-guidelines

Yes for sure..! Since its my first PR for AppFlowy, I was way too excited that I forgot to read the guidelines before commenting.

**Comment by duckcommit** [comment]
> Should we exclude this launch.json file from the commit. cc: @richardshiue

I think it was a mistake from my side. Because the .vscode folder is normally generated by the ide. In case if there is something missing, then it would re-generate the folder. Normally a folder belonging to .gitignore in my pov.

**Pull request merged**
