### PR TITLE
Fix githooks and remove Husky

### PR DESCRIPTION
**Pull request by MikeWallaceDev**
Our current implementation of githooks and Husky did not work. They did nothing.
My research showed that Husky is a JS script tool, and didn't really fit for our needs. So I removed it.
Native githooks will work fine, but require one line of code to be executed, I will document this in the Environment Setup documentation.

I enabled all of the hooks that @appflowy had setup, they all work now.  However, I think that the pre-push hook might be too much and might need to be removed.

CommitLint also now works, I will add the documentation for that too.

### CODE REVIEW

**Comment by appflowy** [comment]
The husky should work by running the `cargo make install-commitlint` script, then you're all set. Also, I had documented it in our [guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request#commit-message-guidelines).

After running the `cargo make install-commitlint`,  my local hook is active.
image

**Comment by appflowy** [comment]
Is there no need to install husky (`cargo make install-commitlint` does) by replacing it with githook? I mean the commit message will be checked automatically on local.

**Comment by MikeWallaceDev** [comment]
You did document it, that's true, but in the wrong place. So people don't see that documentation when they install the environment.

Everything works now, and is simple.  :)

**Comment by appflowy** [comment]
> You did document it, that's true, but in the wrong place. So people don't see that documentation when they install the environment.
> 
> Everything works now, and is simple. :)

Alright, I will try on my local

> You did document it, that's true, but in the wrong place. So people don't see that documentation when they install the environment.
> 
> Everything works now, and is simple. :)

Alright, that's awesome.

**Pull request merged**
