### PR TITLE
fix(network_monitor): add missing case for `other` network type

### PR DESCRIPTION
**Pull request by Merrit**
Missing case causing static analysis error that is blocking the build.

### CODE REVIEW

**Comment by Merrit** [comment]
That's weird - can't build locally because the switch statement doesn't handle the "other" case.

Also the "other" case doesn't exist during CI build..? :thinking:

**Comment by appflowy** [comment]
> That's weird - can't build locally because the switch statement doesn't handle the "other" case.
> 
> Also the "other" case doesn't exist during CI build..? 🤔

The version of the connectivity_plus might be different.

**Comment by Merrit** [comment]
> The version of the connectivity_plus might be different.

Looks like you are right. Thanks!

**Comment by appflowy** [comment]
LGTM

**Pull request merged**
