### PR TITLE
feat: added analysis options + formatted complete code

### LINKED ISSUE #2228: [FR] add prefer_final_fields, prefer_final_in_for_each, prefer_final_locals, prefer_final_parameters to analysis_options.yaml
https://github.com/AppFlowy-IO/AppFlowy/pull/2219/files#diff-821d01a41fc10f7b1d262ae67e55c3c7592a44b0692999b99207dfaaac1dce66R291

* adding the above rules to analysis_options.yaml.
* formatting the exsittng code in the same PR.

### PR DESCRIPTION
**Pull request by yatendra2001**
### Feature Preview

Fixes #2228

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by yatendra2001** [comment]
@LucasXu0 just resolved them, was having some merge conflicts.

**Comment by yatendra2001** [comment]
@LucasXu0 In the mean time we had more commits merged to developer branch, that's why issue with the flutter analyzer is popping out. I'm formatting the code again.

**Comment by LucasXu0** [comment]
Hey, @yatendra2001. No worries. I will do that.

**Comment by yatendra2001** [comment]
Hey @LucasXu0 , since my first PR is merged, I am super excited to participate in Appflowy mentorship program. Just wanted to confirm if it's still running.

Most excited about this project:

AI writers

Utilize AI models to assist in writing. For example, generate to-do lists, outlines, and blog posts.

Difficulty: Medium
Skills Required: Flutter
Mentor: Lucas

**Pull request merged**
