### PR TITLE
Create bn-in

### PR DESCRIPTION
**Pull request by aurkodip**
Bengali (India)

### Feature Preview

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@iaurinko Did you translate the key? There's only an 'English' translation included in your PR.

**Comment by iaurinko** [comment]
will translate from the inlang editor

**Comment by LucasXu0** [comment]
@iaurinko Can you change them in this PR, or should I merge it and then refer to it in inlang?

**Comment by Xazin** [comment]
Hey @iaurinko, can we close this, or will you use this branch/PR for the translations?

**Comment by aurkodip** [comment]
please merge it so that i can translate from the inlang editor

**Comment by LucasXu0** [comment]
Hi, @aurkodip. You can add a new language directly in the Inlang editor. Therefore, I will close it since the translation is incomplete.

Screenshot 2023-09-04 at 10 10 44

And you can refer to this [link](https://inlang.com/documentation/apps/inlang-cli#machine) if you're working with cli.

**Pull request closed without merging**
