### PR TITLE
fix: empty url group bug

### PR DESCRIPTION
**Pull request by zoli**
Moving a row to empty url (no status) group would change the row's url to the group id which is not empty, its a random string. fixed it with puting a check to fill the url with the empty string when the group id is equal to empty url group id.

I'm not sure this is a good way to fix it though.

Continuing from https://github.com/AppFlowy-IO/AppFlowy/pull/1687 and #1175.

### CODE REVIEW

**Comment by zoli** [comment]
Marked this as draft because I see that adding new url doesn't add the new group immediately. You  have to change the group by to other field and again go back to group by url to see the new group.

**Comment by zoli** [comment]
> Marked this as draft because I see that adding new url doesn't add the new group immediately. You have to change the group by to other field and again go back to group by url to see the new group.

OK. I saw that even for group by select removing an option won't remove the group, Is this intended behavior? Also it seems generate group is called (probably from flutter?) for select option changes each time but not for url changes.

**Comment by appflowy** [comment]
> > Marked this as draft because I see that adding new url doesn't add the new group immediately. You have to change the group by to other field and again go back to group by url to see the new group.
> 
> OK. I saw that even for group by select removing an option won't remove the group, Is this intended behavior? Also it seems generate group is called (probably from flutter?) for select option changes each time but not for url changes.

The behaviors of the group are different between different FieldType. I am checking it now.

**Comment by zoli** [comment]
OK, It seems https://github.com/AppFlowy-IO/AppFlowy/commit/069519589e45bea8704801bf1155993d6a50ac0c has fixed the new group and remove group problem.

Still this pr fixes another bug which I mentioned at first: 
> Moving a row to empty url (no status) group would change the row's url to the group id which is not empty, its a random string. fixed it with puting a check to fill the url with the empty string when the group id is equal to empty url group id.

**Comment by appflowy** [comment]
> OK, It seems [0695195](https://github.com/AppFlowy-IO/AppFlowy/commit/069519589e45bea8704801bf1155993d6a50ac0c) has fixed the new group and remove group problem.
> 
> Still this pr fixes another bug which I mentioned at first:
> 
> > Moving a row to empty url (no status) group would change the row's url to the group id which is not empty, its a random string. fixed it with puting a check to fill the url with the empty string when the group id is equal to empty url group id.

Yep. Thank you for contributing.
FYI. I merged the main branch and this PR will be merged after the CI checks.

**Pull request merged**
