### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by Ankkkyyyy**
I added 3 dots for notifying as their are 3 words that is  Website, Discord, Twitter. Their were only 2 Dots, notifying 3 words. So that wasn't looking Professional I feel so I propose this change to Merge this changes in your branch sir.

### CODE REVIEW

**Comment by MikeWallaceDev** [comment]
I leave this up to @annieappflowy, but personally I prefer the original way with 2 dots. It's not a bullet point, it's a separator.

**Comment by Ankkkyyyy** [comment]
That 2 Separator in 3 words doesn't look fit. Rather than that  I suggest to show 3 bullet points according to mee. Am just putting My perspective what I feel. if you @annieappflowy found out my point  okay then merge my  proposed changes Xd. or else don't merge  that's okay that's totally your wish Mam.

**Comment by Hari-07** [comment]
@annieappflowy Please merge or close the issue depending on if the change is required

**Comment by MikeWallaceDev** [comment]
Executive Decision.

**Pull request closed without merging**
