### PR TITLE
Added russian translations

### PR DESCRIPTION
**Pull request by dadyarri**

### CODE REVIEW

**Comment by MikeWallaceDev** [comment]
Hi @dadyarri! Thanks for the PR. Is it still a draft? What's missing? Do you need any assistance?

**Comment by dadyarri** [comment]
> Is it still a draft? What's missing?

Is `flutter pub run easy_localization:generate -S assets/translations/` generates some files?

I don't have enough resources on my machine to work with flutter, so couldn't run it

**Comment by appflowy** [comment]
@dadyarri I start running the GitHub actions and PR will be merged if the CI passed.

**Comment by MikeWallaceDev** [comment]
@dadyarri Thanks for the translation, it works great!

LGTM!

:shipit:

**Comment by dadyarri** [comment]
Hi. Always welcome. Is there a way to subscribe for updates of file with strings, so i could keep translation up-to-date?

**Comment by annieappflowy** [comment]
Hi @fabiograz, do you have a trick here to follow the update of the UI strings?

**Comment by MikeWallaceDev** [comment]
Sorry, I forgot to answer when I researched (because the answer is no :) )
There's no easy way, most of the answers I found would check all the files, I didn't find an easy way to check for one file.

**Comment by dadyarri** [comment]
@MikeWallaceDev guess i've found a way how to do it. Github action that triggers on push to master, filtering by path. Will try to write it

**Pull request merged**
