### PR TITLE
Fix the translation to fr-FR (Closes #369)

### LINKED ISSUE #369: [Bug] Mistakes in the fr.json
**Describe the bug**
There are some mistakes in the FR translation file that i can correct.

@annieappflowy Please assign me 🙏

### PR DESCRIPTION
**Pull request by MidouWebDev**
I worked on reviewing the translation to FR and i found some mistakes that i tried to correct.

This PR is fixing a bug mentionned in #369 

@annieappflowy

### CODE REVIEW

**Comment by MidouWebDev** [comment]
@MikeWallaceDev I updated the changes.
Check https://github.com/AppFlowy-IO/AppFlowy/pull/371/commits/53d3d49b02455f0a73d8051631f9783b429e540a
🙏🏼

**Comment by DevNono** [comment]
Everything is fine according to me except `Favoriser` we should use according to me either `Mettre une étoile sur Github` or `Aimer sur Github`

**Comment by MikeWallaceDev** [comment]
I fixed the commit messages so that the commitlint CI would pass.
I added the language to the system.

**Comment by MikeWallaceDev** [comment]
Thank you very much @MidouWebDev  and @DevNono for improving the french translation!

LGTM!!

:shipit:

**Pull request merged**
