### PR TITLE
feat: improve translations ja_JP

### PR DESCRIPTION
**Pull request by rbdog**
for #3702 

### Feature Preview

brief explanations.

```
L.9 "youCanAlso" 
  old: "あなたもすることができます"
    => this means If I can do it, you can do it too.
  new: "他にもこんなことができます"

L.57 "import"
  old: "輸入"
    => this means importation from abroad 
  new: "取り込む"

L.151 "markdown"
  old: "マークダウンにエクスポートされたノート",
    => not natural
  new: "マークダウン形式のノート",

L.152 "path"
  old: "ドキュメント/フローティ"
    => flowy is 'フローウィー' not 'フローティ', and this path should not be translated 
  new: "Documents/flowy"

L.211 "supabaseSetting"
  old: "スーパーベースの設定"
    => the name 'Supabase' is the same in Japanese
  new: "Supabaseの設定"

L.219 "label"
  old: "Theme Mode"
    => unfamiliar English
  new: "外観テーマ"

L.222 "system"
  old: "Adapt to System"
    => unfamiliar English
  new: "システムと同期"

L.235 "builtInsLabel"
  old: "内蔵テーマ"
    => not natural
  new: "組み込みテーマ"

L.272 "export"
  old: "輸出"
    => This means exportation to abroad 
  new: "書き出す"

L.333 "contains": 
  old: "含まれています"
    => Not bad, but we should standardize the writing style
  new: "を含む"

L.334 "doesNotContain"
  old: "含まれていない"
    => Not bad, but we should standardize the writing style
  new: "を含まない"

L.327 "is"
  old: "は"
    => It lacks the expression of 'equality'
  new: "等しい"

L.328 "isNot": 
  old: "ではありません"
    => not natural
  new: "等しくない"

L.305, 311, 329, 335 "isEmpty": 
  old: "空です"
    => not natural
  new: "空である"

L.306, 311, 330, 335 "isNotEmpty"
  old: "空ではありません"
    => not natural
  new: "空ではない"

L.317 "isUnchecked": 
  old: "チェックなし"
    => there is a better japanese
  new: "未チェック"

L.323 "isComplete": 
  old: "完了しました"
    => there is a better japanese for a status label
  new: "完了"

L.324 "isIncomplted"
  old: "不完全です"
    => not natural
  new: "未完了"

L.370 "newProperty"
  old: "新しい物件"
    => this means a new house
  new: "新しいプロパティ"

L.371 "deleteFieldPromptMessage"
  old: "本気ですか？このプロパティは削除されます"
    => this means 'Are you serious?'
  new: "本当にこのプロパティを削除してもよろしいですか？"

L.374 "ascending": 
  old: "上昇"
    => not natural
  new: "昇順"

L.479 "alertDialogConfirmation"
  old: "よろしいですか、続行しますか?"
    => not natural
  new: "続行しますか？"

L.490 "turnInto" 
  old: "に変わる"
    => not natural
  new: "へ変更"

L.567 "showWeekends"
  old: "週末のショー"
    => this means an entertainment show
  new: "週末を表示する"

L.579 "howToFixFallback"
  old: "... エラーを説明した問題を ..."
    => Issue is better left untranslated as it
  new: "... エラーを説明した issue を ..."
```

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by rbdog** [comment]
#3702

**Comment by LucasXu0** [comment]
@rbdog, thanks for your contribution. Please sign the CLA.

Screenshot 2023-10-15 at 22 09 14

**Comment by rbdog** [comment]
Thank you @LucasXu0
But wait a moment, I might have made a mistake in the **commit comment.**
I didn't include the issue number. 
Can I redo a pull request?

**Comment by rbdog** [comment]
Sorry. I've improved the comments and created a new pull request. #3705

**Pull request closed without merging**
