### PR TITLE
fix: update cn translate

### PR DESCRIPTION
**Pull request by yumin2002**
https://github.com/AppFlowy-IO/AppFlowy/issues/2049
---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by hyj1204** [comment]
The tooltip of more button needs translation
image

**Comment by yumin2002** [comment]
Thanks for checking, I’ll add that later. Please also post any other
missing translation if any! I’ ll keep working on that.

Yijing Huang ***@***.***>于2023年5月23日 周二12:46写道：

**Review by hyj1204 — APPROVED** [review]
LGTM

**Comment by yumin2002** [comment]
In additon to the text in the AppFlowy editor, there are some translations using
Screen Shot 2023-05-23 at 17 29 15,
which resulted in the following: 
Screen Shot 2023-05-23 at 17 28 51
the translation supposed to be: "网格来自参考页".
This is also sth we can open a separate issue to address.

**Comment by yumin2002** [comment]
Another issue that I found is sth I do not know how to fix without looking into the code, since "Lavender" does not exist in en.json, I will open a separate issue for this: 
Screen Shot 2023-05-23 at 17 34 33

**Pull request merged**
