### PR TITLE
Resolve rust clippy warnings

### PR DESCRIPTION
**Pull request by gabrielztk**
Resolved warnings given by clippy, and refactored some of the affected snippets so they would be more inline with Cascade Notation (most commit messages pertain to the warning that section of code gave)

I began this task based on #221, but it has already been closed.

Only one warning was left, as resolving it, from what I understood, would change the projects architecture

warning: module has the same name as its containing module
 --> lib-ot/src/core/document/mod.rs:2:1
  |
2 | mod document;
  | ^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::module_inception)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_inception

### CODE REVIEW

**Comment by appflowy** [comment]
> 



> Resolved warnings given by clippy, and refactored some of the affected snippets so they would be more inline with Cascade Notation (most commit messages pertain to the warning that section of code gave)
> 
> I began this task based on #221, but it has already been closed.
> 
> Only one warning was left, as resolving it, from what I understood, would change the projects architecture
> 
> warning: module has the same name as its containing module --> lib-ot/src/core/document/mod.rs:2:1 | 2 | mod document; | ^^^^^^^^^^^^^ | = note: `#[warn(clippy::module_inception)]` on by default = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_inception

We could use #![allow(clippy::module_inception)] to ignore the warnings. I do the same thing in multiple places. It seems it's not a good idea. Maybe we should rename the file to fix this error.

**Review by vincentdchan — APPROVED** [review]

**Comment by appflowy** [comment]
@gabrielztk There is a Rust lint error in ci. You could try `cargo fmt -all -- --check` in lib-ot crate to find out the errors.

**Comment by gabrielztk** [comment]
Fixed the formatting warnings on lib-ot crate @appflowy 
How should I make new commits as not to get the body-leading-blank complains?

**Comment by appflowy** [comment]
Hi, @gabrielztk I rebased the main branch into your branch.

**Comment by gabrielztk** [comment]
Thanks @appflowy!
This was my first PR to an open source project, you were very helpful

**Comment by annieappflowy** [comment]
@gabrielztk congrats, and well done!

**Pull request merged**
