### PR TITLE
fix: update the language according to the setting when launching

### PR DESCRIPTION
**Pull request by yumin2002**
https://github.com/AppFlowy-IO/AppFlowy/issues/2500
---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by yumin2002** [comment]
Original buggy outcome when launching: 
language setting is Chinse while the interface is in english.
Screen Shot 2023-05-22 at 00 26 33
Current outcome: 
Screen Shot 2023-05-22 at 00 26 02

**Comment by yumin2002** [comment]
In addition, I have testing item in the list unchecked. I am a little confused about testing. Anyone would like to share a little bit about how to write test for this? Thanks!

**Comment by LucasXu0** [comment]
@yumin2002 Just let me know if you need any further assistance.

For the case you fixed, you can add a test like this:

1. Launch the app.
2. Open the settings page by simulating a click.
3. Change the language.
4. Re-launch the app.
5. Open the settings page again and verify the language.

**Comment by LucasXu0** [comment]
And please submit this PR to the develop branch.

**Pull request closed without merging**
