### PR TITLE
feat: added multiple params to analysis_options.yaml

### LINKED ISSUE #2228: [FR] add prefer_final_fields, prefer_final_in_for_each, prefer_final_locals, prefer_final_parameters to analysis_options.yaml
https://github.com/AppFlowy-IO/AppFlowy/pull/2219/files#diff-821d01a41fc10f7b1d262ae67e55c3c7592a44b0692999b99207dfaaac1dce66R291

* adding the above rules to analysis_options.yaml.
* formatting the exsittng code in the same PR.

### PR DESCRIPTION
**Pull request by yatendra2001**
### Feature Preview

Fixes #2228 

---

#### PR Checklist

- [x] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [x] I've listed at least one issue that this PR fixes in the description above.
- [x] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [x] All existing tests are passing.

### CODE REVIEW

**Comment by yatendra2001** [comment]
@LucasXu0 I've fixed issue #2228 

Let me know if any further changes are needed.

**Comment by LucasXu0** [comment]
Hey, @yatendra2001. I suppose you should format the code too. You can try to use `dart fix --apply`

**Comment by LucasXu0** [comment]
FYI, please submit your PR based on the develop branch.

**Comment by yatendra2001** [comment]
@LucasXu0 I actually forked the main branch of appflowy and now merging it to develop branch causing too many conflicts. 
I reckon I  must create a new fork, make changes to the forked develop branch and then create a new PR right?
WDYT?

**Comment by LucasXu0** [comment]
@yatendra2001 Yes. Let me close this PR. You should fork the develop branch and submit a new PR.

**Pull request closed without merging**
