### PR TITLE
feat: can transform options from single & multi select

### PR DESCRIPTION
**Pull request by ENsu**

### CODE REVIEW

**Comment by appflowy** [comment]
Hi, @ENsu Thank you for contributing. It would be better if we have unit tests for these changes. We have lots of tests in flowy-grid/tests folder, you can have a look and feel free to ask me if you have any questions on discord.

**Comment by ENsu** [comment]
Got it! No problem, I'll work on it!

**Comment by ENsu** [comment]
@appflowy I can't seem to find the function called `grid_switch_from_checkbox_to_select_option_test`; do you mean single `single_select_transform_with_checkbox_type_option_test`?

**Comment by appflowy** [comment]
> grid_switch_from_checkbox_to_select_option_test

You have to pull the latest code because I created this test, `grid_switch_from_checkbox_to_select_option_test` after reviewing your pr.

**Review by appflowy — APPROVED** [review]

**Pull request merged**
