### PR TITLE
chore: update German translations to state of v0.6.7

### PR DESCRIPTION
**Pull request by suntorytimed**
I have updated the German translation for v0.6.6 and included some minor translation fixes of prior translations in the wording of the "Grid".

Preview the messages on https://inlang.com/github.com/suntorytimed/AppFlowy .

### CODE REVIEW

**Comment by suntorytimed** [comment]
@LucasXu0 @Xazin now that the itemThree issue is resolved a new empty itemSeven has been added, resulting in the same InLang issue:

```
        "itemThree": "5 GB",
        "itemFour": "yes",
        "itemFive": "yes",
        "itemSix": "100 lifetime",
        "itemSeven": ""
        "itemSix": "100 lifetime"
```

I will fix this by hand in this pull request.

**Comment by Xazin** [comment]
> @LucasXu0 @Xazin now that the itemThree issue is resolved a new empty itemSeven has been added, resulting in the same InLang issue:
> 
> I will fix this by hand in this pull request.

Feel free to completely remove `itemSeven` from the code as well.

**Comment by suntorytimed** [comment]
@Xazin as far as I can tell this has been the fix for the last time this happened: https://github.com/AppFlowy-IO/AppFlowy/pull/5737/commits/42141fe9cf22aba9c144d021c820848ab4511fe4

I would do it the same way for now.

**Comment by Xazin** [comment]
I've added a commit to your branch and removed `itemSeven` completely :pray:

**Comment by annieappflowy** [comment]
Hi @suntorytimed , could you help us translate Spaces, Recent, and Favorites into shorter German words? The current translation is too long to look good on mobile:
image

**Comment by suntorytimed** [comment]
@annieappflowy yes, I will have a look into it.

**Comment by suntorytimed** [comment]
Added shorter translations, which should fix the mobile layout.

**Comment by annieappflowy** [comment]
Thank you, @suntorytimed  ❤️

**Comment by suntorytimed** [comment]
@Xazin the tests complain about the changes in lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart

```
  error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:703:5 • extra_positional_arguments_could_be_named
  error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:707:5 • extra_positional_arguments_could_be_named
  error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:733:5 • extra_positional_arguments_could_be_named
  error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:737:5 • extra_positional_arguments_could_be_named
```

**Comment by Xazin** [comment]
> @Xazin the tests complain about the changes in lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
> 
> ```
>   error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:703:5 • extra_positional_arguments_could_be_named
>   error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:707:5 • extra_positional_arguments_could_be_named
>   error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:733:5 • extra_positional_arguments_could_be_named
>   error • Too many positional arguments: 0 expected, but 1 found • lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart:737:5 • extra_positional_arguments_could_be_named
> ```
> 
> I assume this is due to resolving the merge conflict with main: [d6c1067#diff-eab7e9f2fdfb720ab56beb0e87dab0c8864c4a06147be0c7ee260e398b37269e](https://github.com/AppFlowy-IO/AppFlowy/commit/d6c10678b6fcbf796c11f897b6b21b14af9c581d#diff-eab7e9f2fdfb720ab56beb0e87dab0c8864c4a06147be0c7ee260e398b37269e)

I will push a fix, thanks for letting me know :+1:

**Comment by Xazin** [comment]
I've resolved the issue. :+1:

**Comment by suntorytimed** [comment]
@LucasXu0 @Xazin as far as I can tell nothing else should block this PR, right? The codecov result should be unrelated to the translation changes.

**Comment by suntorytimed** [comment]
added translation of latest strings in main

**Review by LucasXu0 — APPROVED** [review]

**Pull request merged**
