### PR TITLE
fix:Better wording for German i18n

### PR DESCRIPTION
**Pull request by math-GH**
Hi,
this is my first PR here. I hope it is fine, if not please ping me to improve my PR.

### Feature Preview
some better translations for the German UI

#### PR Checklist

- [x] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by math-GH** [comment]
CLA is assigned but the pipeline does not recognize it

grafik

grafik

**Comment by richardshiue** [comment]
Hey there @math-GH thanks for the contribution! Could you make sure that the email you used to make your commit is the same as, or is the noreply version of the email on your Github account? You can check this page https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by math-GH** [comment]
ah ok, the link helped me a lot. I will create a new PR with the (hopefully) correct email address.

**Comment by math-GH** [comment]
see #4227

**Pull request closed without merging**
