### PR TITLE
refactor: Migrate the markdown feature from Dart to Rust

### PR DESCRIPTION
**Pull request by matrixhead**
#357

### CODE REVIEW

**Comment by appflowy** [comment]
Thank you for contributing!  I found you had written some unit tests! That's awesome! 

I recommend that you could split the test into multiple tests. Each test should be small enough to find out why it succeeds or fails. For example:


```rust
#[cfg(test)]
mod tests {
    #[test]
    fn markdown_encoder_test_header1() {
        // Do something
    }
    #[test]
    fn markdown_encoder_test_header2() {
        // Do something
    }
    #[test]
    fn markdown_encoder_test_bold() {
        // Do something
    }
}
```

**Comment by appflowy** [comment]
The rust lint test failed in CI. You could run in lib-ot crate: 
`cargo fmt --all -- --check`

Also, you can use  `cargo fmt --all` to fix all the lint warnings. But make sure the changes before submitting.

**Comment by matrixhead** [comment]
sure i will try to fix all of these

**Comment by IMPranshu** [comment]
> sure i will try to fix all of these

Hey, @matrixhead great contribution. I wanted to ask does this PR closes any specific issue from the issue section. Can you please mention that issue here so that the issue will be tracked and closed automatically?

**Comment by matrixhead** [comment]
@IMPranshu yeah it does thanks for reminding me i added it in the description

**Pull request merged**
