### PR TITLE
test: attempt to fix failing windows test

### PR DESCRIPTION
**Pull request by Xazin**
### Feature Preview

---

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

### CODE REVIEW

**Comment by LucasXu0** [comment]
@Xazin Did you reproduce the error on your side?

**Comment by Xazin** [comment]
> @Xazin Did you reproduce the error on your side?

No not yet, I'm trying a few things right now, cross-referencing the errors from the pipelines.

**Comment by LucasXu0** [comment]
> > @Xazin Did you reproduce the error on your side?
> 
> No not yet, I'm trying a few things right now, cross-referencing the errors from the pipelines.

Okay. I attempted to fix it, but I am unable to reproduce it on my Windows system.

**Comment by Xazin** [comment]
Will try the following next week:
- Changing the Runner to another non-default runner
- Extending execution time of specific integration tests
- Custom Windows Agent if possible (Eg. own PC, or Azure Instance)

**Pull request closed without merging**
