### PR TITLE
chore: bump collab and client api

### PR DESCRIPTION
**Pull request by appflowy**
We're currently enhancing AppFlowy Cloud to include team collaboration features. However, integrating these features with Supabase as the server option is proving to be more complex and requires additional work. As a result, we've decided to temporarily disable the option to use Supabase until we can fully support team collaboration functionalities with it.

### CODE REVIEW

**Comment by allenlinli** [comment]
Looking forward to see it support Supabase again 💪

**Comment by minskmaz** [comment]
There is a note in the May 7, 2024 - v0.5.6 release that Teams is live.. but when downloading it no such feature is present in the settings.

**Comment by bitnom** [comment]
Is there a discussion of the reasoning behind this decision? As a Supabase customer, I'm well aware of some of its limitations. I'm just curious how it turned out this way for you.

**Comment by ThuggishNuggets** [comment]
> Is there a discussion of the reasoning behind this decision? As a Supabase customer, I'm well aware of some of its limitations. I'm just curious how it turned out this way for you.

 I second this.  Is there any documentation or conversation somewhere on why this decision was made?

Is there any word on the support being added back anytime soon?

At this point it is starting to look like SupaBase support was dropped because it was the free option.  Now the project is steeped in a bunch of AI and proprietary cloud software like AWS S3 and Redis, and doesn’t even support the use case that many of us we’re interested  in it for in the first place which is really unfortunate.

I think we’re all trying to get out from underneath the thumb of all the big tech companies to some extent or another. Redis changed their license so they aren’t even FOSS anymore.

Thanks

**Comment by annieappflowy** [comment]
@ThuggishNuggets , 
You mentioned, "At this point, it is starting to look like SupaBase support was dropped because it was the free option."
**Just to clarify, that wasn’t our intention.**

We decided to sunset Supabase because of the need for multi-user collaborative editing. If you know any ways to make Supabase support real-time collaboration, we’d love to hear them!

That said, you might still use Supabase just for the Postgres part, like how RDS on AWS or Cloud SQL on GCP are used. (See [this post](https://www.reddit.com/r/Supabase/comments/165aju1/are_some_of_you_using_supabase_just_for_the/).) But we’ll need to do some more research. There are also free alternatives (see my reply below).

You also commented, "Now the project is steeped in a bunch of AI and proprietary cloud software like AWS S3 and Redis."
**That’s _not true_.**

AWS S3 is not a hard requirement. There are many S3-compatible storage, such as Minio (can be self hosted), CloudFlare (not free above certain usage). 

Some AppFlowy self-hosters use Minio, Cloudflare, or even skip cloud providers altogether by setting up their own servers at home. You’re welcome to join our Discord server to see which cloud providers others use to self-host AppFlowy.

And a good thing of moving away from Supabase, is that we have user base who set up home lab at home, who already have their own postgres and would rather not self host the entire Supabase system just for AppFlowy.

As for AI, we believe it’s a big part of the future, so we want to invest in it. We understand if you feel differently, though.
image

**Comment by aroseking** [comment]
my all email could not receive the magic link

**Comment by iAndroS** [comment]
- If you know any ways to make Supabase support real-time collaboration, we’d love to hear them!
- Convex???

**Pull request merged**
